// Generated by scripts/gen-script-docs.mjs from content/script/nav.json. Do not edit.
import ScriptDocView, { scriptDocMetadata } from "@/components/script/ScriptDocView"

export const metadata = scriptDocMetadata("strategies", "exits-and-brackets")

export default function Page() {
  return <ScriptDocView section={"strategies"} page={"exits-and-brackets"} />
}
