// Single source of truth for the "AmiBroker AFL" learning portal:
// 36 chapters across 8 modules. Slugs form the /amibroker/<slug> URLs - keep them stable.

export const SERIES_TITLE = "AmiBroker AFL";
export const SERIES_SUB =
  "A hands-on, beginner-to-intermediate course in AmiBroker Formula Language (AFL) - build indicators, scanners, systems and live automation, explained in plain English.";

export const PARTS = [
  {
    id: "A",
    name: "Meet AmiBroker",
    desc: "What AmiBroker is, how the Formula Editor works, and the one idea - arrays - that makes AFL click.",
    chapters: [
      { slug: "what-is-amibroker", title: "What is AmiBroker & AFL",
        summary: "The big picture - charts, the Analysis window, and the four things AFL can do: indicate, explore, scan and backtest.",
        learn: ["What AmiBroker is for", "Indicator vs Exploration vs Backtest", "Where AFL code lives",
          "The Formula Editor & Apply", "Chart panes & sheets", "How this course is structured"], tags: ["Basics"] },
      { slug: "formula-editor", title: "The Formula Editor & Your First Indicator",
        summary: "Write, apply and save your first AFL - a one-line RSI plot - and learn the editor habits that save hours.",
        learn: ["Open the Formula Editor", "_SECTION_BEGIN / _SECTION_END", "Comments & readability",
          "Plot() your first line", "Apply Indicator vs Insert", "Saving & organising formulas"], tags: ["Basics", "AFL"] },
      { slug: "how-afl-thinks", title: "How AFL Thinks: Arrays & Bars",
        summary: "The single most important idea in AFL - every variable is a whole array of values, one per bar. Get this and everything else is easy.",
        learn: ["What an array really is", "One value per bar", "Vectorised vs bar-by-bar thinking",
          "The current bar vs the array", "Why there are almost no loops", "Visualising arrays as columns"], tags: ["Basics", "AFL"] },
      { slug: "price-and-variables", title: "Price Arrays, Variables & Operators",
        summary: "Meet O, H, L, C, V and Volume, store results in variables, and do maths across an entire chart at once.",
        learn: ["Open/High/Low/Close/Volume arrays", "Assigning variables", "Arithmetic across arrays",
          "Typical price & ranges", "Operators & precedence", "Reading the chart's data window"], tags: ["Basics", "AFL"] },
    ],
  },
  {
    id: "B",
    name: "The AFL Language",
    desc: "The grammar of AFL - plotting, parameters, built-in functions, logic, looking back, and writing your own functions.",
    chapters: [
      { slug: "plotting-and-styles", title: "Plotting & Chart Styles",
        summary: "Draw lines, candles, histograms and bands - and control colour, thickness and style like a pro.",
        learn: ["Plot() in depth", "styleLine / styleCandle / styleHistogram", "GetPriceStyle & styleNoTitle",
          "Colours and colorXXX constants", "Combining styles with |", "Plotting in a new pane"], tags: ["Chart", "AFL"] },
      { slug: "parameters", title: "Parameters: Interactive Controls",
        summary: "Turn hard-coded numbers into sliders, colour pickers and dropdowns with Param, ParamColor, ParamList and friends.",
        learn: ["Param() sliders", "ParamColor & ParamStyle", "ParamList & ParamToggle",
          "ParamTrigger buttons", "Why parameters beat magic numbers", "The Parameters window"], tags: ["Chart", "AFL"] },
      { slug: "built-in-functions", title: "Built-in Functions & Indicators",
        summary: "A guided tour of the functions you will use every day - MA, EMA, RSI, MACD, ATR, BBands and how to read the function reference.",
        learn: ["Moving averages: MA, EMA, WMA", "RSI, MACD, Stochastic", "ATR & Bollinger Bands",
          "Sum, Highest, Lowest, HHV, LLV", "Reading the AFL function reference", "Nesting functions"], tags: ["Indicator", "AFL"] },
      { slug: "conditions-and-logic", title: "Conditions, Logic & IIf",
        summary: "Build true/false arrays with comparisons and AND/OR, then choose values bar-by-bar with the all-important IIf.",
        learn: ["Comparison operators", "AND, OR, NOT on arrays", "True/false as 1/0",
          "IIf(condition, a, b)", "Nesting IIf", "Common logic mistakes"], tags: ["AFL"] },
      { slug: "referencing-bars", title: "Looking Back: Ref, Cross & BarsSince",
        summary: "Reach into earlier (and later) bars with Ref, detect crossovers with Cross, and count bars since an event.",
        learn: ["Ref() to shift an array", "Yesterday's close, prior high", "Cross() for crossovers",
          "BarsSince & Barssince logic", "HHV / LLV over a window", "Avoiding look-ahead bias"], tags: ["AFL"] },
      { slug: "dates-and-sessions", title: "Dates, Times & the Trading Session",
        summary: "Read the calendar and the clock - Day, Month, time-of-day - and answer the question every intraday system asks: has a new day started?",
        learn: ["Day / Month / Year / DayOfWeek", "TimeNum & the HHMMSS clock", "Detecting a new day or session",
          "Bars since the open; first & last bar of the day", "The day's open, high & low so far", "Restricting entries to a time window"], tags: ["AFL", "Realtime"] },
      { slug: "arrays-and-loops", title: "Arrays vs Loops: the for-loop",
        summary: "Most AFL needs no loops - but some logic (like a trailing stop) does. Learn when and how to write a clean for-loop.",
        learn: ["When arrays are not enough", "for( i = 0; i < BarCount; i++ )", "Indexing an array with [i]",
          "Carrying state across bars", "A simple trailing-stop loop", "Loop performance & pitfalls"], tags: ["AFL"] },
      { slug: "custom-functions", title: "Custom Functions & Procedures",
        summary: "Package logic you reuse into your own functions and procedures, with local and global scope.",
        learn: ["function vs procedure", "Parameters & return", "local vs global variables",
          "Returning an array", "A reusable indicator function", "Building a small personal library"], tags: ["AFL"] },
    ],
  },
  {
    id: "C",
    name: "Charting & Visualisation",
    desc: "Make charts that communicate - arrows, colour-coded candles, dynamic titles, multi-pane layouts and GFX dashboards.",
    chapters: [
      { slug: "shapes-and-text", title: "Arrows, Shapes & Text",
        summary: "Mark signals on the chart with PlotShapes and PlotText - up arrows, down arrows, stars and labels.",
        learn: ["PlotShapes & shapeUpArrow", "Positioning with Offset", "Colour by condition",
          "PlotText for labels", "Stacking shapes", "Buy/Sell arrow conventions"], tags: ["Chart"] },
      { slug: "color-coding", title: "Colours, Ribbons & Conditional Candles",
        summary: "Colour candles by trend, paint background ribbons and build at-a-glance visual context.",
        learn: ["IIf-driven colours", "Colouring candles by a rule", "Trend ribbons at the bottom",
          "Background shading", "MACD / RSI colour coding", "colorXXX vs ColorRGB"], tags: ["Chart"] },
      { slug: "title-and-strformat", title: "The Title Bar & StrFormat",
        summary: "Build a rich, dynamic chart header - name, OHLC, percent change - with Title, StrFormat and WriteIf.",
        learn: ["The Title variable", "StrFormat & format specifiers", "{{NAME}}, {{DATE}} tokens",
          "NumToStr & WriteIf", "SelectedValue for the cursor", "A professional header"], tags: ["Chart"] },
      { slug: "panes-and-foreign", title: "Multiple Panes & Comparing Symbols",
        summary: "Stack indicator panes, and pull in another symbol's data with Foreign and PlotForeign for relative strength.",
        learn: ["New pane vs overlay", "Foreign() to read another symbol", "PlotForeign on the chart",
          "Relative strength vs an index", "SetForeign / RestorePriceArrays", "Spread & ratio charts"], tags: ["Chart"] },
      { slug: "gfx-dashboards", title: "GFX Dashboards",
        summary: "Draw your own panels - boxes, gradients and text - with the low-level GFX functions for a polished dashboard.",
        learn: ["GfxText & GfxSelectFont", "GfxRectangle & GfxGradientRect", "Coordinates & pixels",
          "A signal status box", "A responsive top dashboard", "When GFX is worth it"], tags: ["Chart"] },
    ],
  },
  {
    id: "D",
    name: "Exploration & Scanning",
    desc: "Screen the whole market at once - the Analysis window, AddColumn, filters and ranking.",
    chapters: [
      { slug: "exploration-basics", title: "Exploration: the Analysis Window",
        summary: "Turn AFL into a spreadsheet over your whole watchlist with Filter and AddColumn.",
        learn: ["The Analysis window", "Filter = the row switch", "AddColumn & AddTextColumn",
          "Decimal formatting", "Running over a watchlist", "Range, date and N-bars settings"], tags: ["Exploration"] },
      { slug: "building-a-scanner", title: "Building a Signal Scanner",
        summary: "Scan dozens of symbols for a real setup - MACD crosses, RSI extremes and breakouts - and list only the hits.",
        learn: ["Filtering to signals only", "MACD / RSI scanners", "Breakout & 52-week scans",
          "Showing the trigger value", "Scan vs Explore", "Saving an analysis project"], tags: ["Exploration"] },
      { slug: "ranking-and-filtering", title: "Filtering, Sorting & Ranking",
        summary: "Sort the results, colour the cells, and rank your universe by strength or volume.",
        learn: ["Multi-condition filters", "Sorting columns", "Conditional cell colour",
          "Relative-volume ranking", "Highlighting the best", "Exploration as a daily routine"], tags: ["Exploration"] },
    ],
  },
  {
    id: "E",
    name: "Building Trading Systems",
    desc: "The mechanics of a tradable system - signals, clean entries and exits, stops, targets and sizing.",
    chapters: [
      { slug: "buy-sell-signals", title: "Buy, Sell, Short & Cover",
        summary: "The four reserved arrays that turn an idea into a system - and how AmiBroker reads them.",
        learn: ["Buy / Sell / Short / Cover", "Long-only vs long-short", "Signals are true/false arrays",
          "BuyPrice & friends", "From indicator to system", "The trade lifecycle"], tags: ["Strategy"] },
      { slug: "cleaning-signals", title: "Clean Signals: ExRem, Flip & No Repainting",
        summary: "Remove duplicate signals with ExRem, hold state with Flip, and delay one bar so your system never repaints.",
        learn: ["Why raw signals repeat", "ExRem to keep the first", "Flip for stateful holds",
          "Ref(-1) to avoid repainting", "SetTradeDelays", "ValueWhen for entry prices"], tags: ["Strategy"] },
      { slug: "stops-and-targets", title: "Stops, Targets & ApplyStop",
        summary: "Add a stop-loss and profit target - both as visual chart levels and as real backtest exits with ApplyStop.",
        learn: ["Fixed & percent stops", "ATR-based stops", "Visual stop/target plots",
          "ApplyStop stopTypeLoss / Profit", "Trailing stops", "Stops in the backtest"], tags: ["Strategy"] },
      { slug: "position-sizing", title: "Position Sizing & Trade Delays",
        summary: "Control how much you trade with SetPositionSize, and when fills happen with SetTradeDelays and SetOption.",
        learn: ["SetPositionSize modes", "Percent of equity vs fixed", "spsShares / spsValue",
          "SetTradeDelays explained", "Initial equity & commissions", "Margin & leverage"], tags: ["Strategy"] },
    ],
  },
  {
    id: "F",
    name: "Backtesting & Optimisation",
    desc: "Prove an edge before risking capital - run a backtest, read the report, and optimise without fooling yourself.",
    chapters: [
      { slug: "first-backtest", title: "Your First Backtest",
        summary: "Run a full backtest in the Analysis window, set the date range and settings, and see your equity curve.",
        learn: ["From chart to backtest", "Backtest settings", "Date range & periodicity",
          "Running a backtest", "The equity curve", "Common setup mistakes"], tags: ["Backtest"] },
      { slug: "backtest-report", title: "Reading the Backtest Report",
        summary: "Make sense of the numbers - net profit, CAR, drawdown, win rate, payoff and the risk-adjusted ratios.",
        learn: ["Net profit & CAR", "Max drawdown & MAR", "Win rate & payoff ratio",
          "Sharpe & expectancy", "Per-trade list", "Red flags in a report"], tags: ["Backtest"] },
      { slug: "optimization", title: "Optimisation & Robustness",
        summary: "Sweep parameters with Optimize(), read the results, and choose robust settings - not just the curve-fit peak.",
        learn: ["Optimize() in place of Param", "Running an optimisation", "Reading the result table",
          "2D heatmaps", "Robust vs peak settings", "Avoiding over-fitting"], tags: ["Backtest"] },
    ],
  },
  {
    id: "G",
    name: "Strategy Playbook",
    desc: "Five complete, explained systems - each one ready for you to backtest and drop your own report images into.",
    chapters: [
      { slug: "ema-crossover-system", title: "Strategy: EMA Crossover System",
        summary: "The classic trend system, built end-to-end - signals, arrows, delays and a backtest you can run yourself.",
        learn: ["Fast/slow EMA logic", "Clean long & short signals", "Plotting the system",
          "Backtest setup", "Reading its report", "Tuning the periods"], tags: ["Strategy", "Backtest"] },
      { slug: "supertrend-system", title: "Strategy: Supertrend System",
        summary: "Build the popular ATR-based Supertrend from scratch with a for-loop, plot the trailing stop, and trade it.",
        learn: ["The Supertrend idea", "ATR bands & the loop", "Trend state & flips",
          "Trailing-stop plot", "Signals & backtest", "Factor & period tuning"], tags: ["Strategy", "Backtest"] },
      { slug: "vwap-intraday-system", title: "Strategy: VWAP Intraday System",
        summary: "An intraday mean-reversion / trend system around VWAP, with time-based entries and a session reset.",
        learn: ["What VWAP is", "Building intraday VWAP", "Session-aware logic",
          "Entries around VWAP", "Time-based exits", "Intraday backtest notes"], tags: ["Strategy", "Backtest"] },
      { slug: "breakout-system", title: "Strategy: Donchian / Opening-Range Breakout",
        summary: "Two breakout classics - the Donchian channel and the opening-range breakout - coded and ready to test.",
        learn: ["Donchian highest/lowest", "Channel breakout entries", "Opening-range levels",
          "Time windows intraday", "Stops on a breakout", "Backtesting breakouts"], tags: ["Strategy", "Backtest"] },
      { slug: "rsi-pullback-system", title: "Strategy: RSI Pullback & Mean Reversion",
        summary: "A counter-trend pullback system using RSI with a trend filter - buying dips in an uptrend.",
        learn: ["RSI as a pullback trigger", "Trend filter with EMA", "Entry & exit rules",
          "Avoiding falling knives", "Backtest & expectancy", "Long-only vs both sides"], tags: ["Strategy", "Backtest"] },
    ],
  },
  {
    id: "H",
    name: "Real-Time, Alerts & Automation",
    desc: "Take a system live - multiple time frames, alerts to your phone, and order automation through OpenAlgo.",
    chapters: [
      { slug: "multi-timeframe", title: "Multiple Time Frames",
        summary: "Read a higher time frame on a lower-time-frame chart with TimeFrameSet, TimeFrameGetPrice and friends.",
        learn: ["Why multi-timeframe", "TimeFrameSet / Restore", "TimeFrameGetPrice",
          "TimeFrameExpand", "A higher-TF trend filter", "Pitfalls & alignment"], tags: ["Realtime"] },
      { slug: "alerts", title: "Alerts: Telegram & Voice",
        summary: "Fire alerts the moment a signal triggers - on-chart AlertIf, a Telegram message, and a spoken voice alert.",
        learn: ["AlertIf basics", "Suppressing repeats", "Telegram bot alerts",
          "InternetOpenURL", "Voice (Say) alerts", "Once-per-bar logic"], tags: ["Realtime"] },
      { slug: "openalgo-automation", title: "Automating Orders with OpenAlgo",
        summary: "Send your AFL signals to OpenAlgo to place real orders - button and signal-based automation, in sandbox first.",
        learn: ["AmiBroker to OpenAlgo", "The order API call", "Button trading module",
          "Signal-based auto orders", "Sandbox (analyzer) mode first", "Safety & confirmation"], tags: ["Realtime", "OpenAlgo"] },
      { slug: "whats-next", title: "Where to Go Next",
        summary: "A map of what you have learned, the parts of AFL still to explore, and how to keep getting better.",
        learn: ["What you can now build", "Areas to go deeper", "Good habits & version control",
          "The function reference", "Joining the community", "From AFL to a full workflow"], tags: ["Basics"] },
    ],
  },
];

// Chapter numbers are assigned automatically by position, so inserting a chapter
// anywhere in PARTS needs no manual renumbering.
let _n = 0;
for (const _p of PARTS) for (const _c of _p.chapters) _c.n = ++_n;

export const CHAPTERS = PARTS.flatMap((p) =>
  p.chapters.map((c) => ({ ...c, part: p.id, partName: p.name }))
).sort((a, b) => a.n - b.n);

export function chapterBySlug(slug) {
  return CHAPTERS.find((c) => c.slug === slug) || null;
}

export const TAG_CLASS = {
  Basics: "idx",
  AFL: "afl",
  Chart: "nfo",
  Indicator: "nse",
  Exploration: "mcx",
  Strategy: "us",
  Backtest: "live",
  Realtime: "py",
  Options: "idx",
  OpenAlgo: "afl",
};
