// Single source of truth for the "Python for Traders" learning portal:
// 40 chapters across 5 modules - an absolute-beginner path into Python for
// finance. Pure Python (no trading-SDK code in the lessons), taught
// Zerodha-Varsity style, with real US data from yfinance and live Indian data
// from OpenAlgo only where a chapter genuinely needs it.
// Slugs form the /fundamentals/<slug> URLs - keep them stable.

export const SERIES_TITLE = "Python for Traders";
export const SERIES_SUB =
  "Never written a line of code? Start here. A hands-on, 40-chapter path that takes a trader or investor from zero to confidently handling real market data in Python - one small, friendly step at a time.";

export const PARTS = [
  {
    id: "1",
    name: "Getting Started with Python",
    desc: "From zero to your first script - install Python, meet your tools, and learn the absolute basics.",
    chapters: [
      { n: 1, slug: "why-python-for-finance", title: "Why Python for Finance",
        summary: "Why the world's trading desks run on Python - and the surprising reason a 'slow' language is actually fast where it counts.",
        learn: ["Why traders learn Python", "Is Python really slow?", "Python as glue: C & Rust cores",
          "NumPy vs pure Python (30x)", "Who uses Python on the Street", "How this course works"], tags: ["PY"] },
      { n: 2, slug: "installing-python", title: "Installing Python & pip",
        summary: "Get Python onto your computer the painless way, and meet pip - the tool that installs everything else you'll use.",
        learn: ["Download & install Python", "Windows vs Mac notes", "Checking your version",
          "What pip is", "Your first terminal command", "Avoiding common setup traps"], tags: ["PY"] },
      { n: 3, slug: "vscode-and-jupyter", title: "Your Toolkit: VS Code & Jupyter",
        summary: "Set up a clean, friendly place to write code - and meet Jupyter, the notebook traders love for poking at data.",
        learn: ["Installing VS Code", "Running your first .py file", "What a Jupyter notebook is",
          "Cells & interactive output", "Editor vs notebook", "A comfortable setup"], tags: ["PY"] },
      { n: 4, slug: "variables-and-comments", title: "Variables & Comments",
        summary: "Store a price, a symbol, a quantity - and leave notes for your future self. The humble building block of every program.",
        learn: ["What a variable is", "Storing prices & symbols", "Good variable names",
          "Reassigning values", "Writing comments", "Reading code aloud"], tags: ["PY"] },
      { n: 5, slug: "numbers-and-types", title: "Numbers & Data Types",
        summary: "Integers, decimals, text and true/false - the basic kinds of data, and how to turn one into another.",
        learn: ["int, float, str, bool", "The type() function", "Whole numbers vs decimals",
          "Converting between types", "Rounding money correctly", "Truthy values"], tags: ["PY"] },
      { n: 6, slug: "operators", title: "Operators & P&L Math",
        summary: "Add, subtract, compare and combine - using Python as a calculator to work out profit, loss and percentage moves.",
        learn: ["Arithmetic operators", "Computing profit & loss", "Percentage change",
          "Comparison operators", "Logical and / or / not", "Operator precedence"], tags: ["PY"] },
      { n: 7, slug: "input-output-fstrings", title: "Input, Output & f-strings",
        summary: "Print results clearly and read input - and format rupees, dollars and percentages so they actually look right.",
        learn: ["The print() function", "Reading input()", "f-strings explained",
          "Formatting money & %", "Rounding in output", "Multi-line output"], tags: ["PY"] },
      { n: 8, slug: "strings", title: "Working with Strings",
        summary: "Symbols, tickers and dates are all text. Slice them, clean them and reshape them with Python's string toolkit.",
        learn: ["Strings as text", "Indexing & slicing", "Upper, lower & strip",
          "split & join", "Checking & replacing", "Building ticker strings"], tags: ["PY", "NSE"] },
    ],
  },
  {
    id: "2",
    name: "Core Programming",
    desc: "The building blocks every program is made of - data structures, logic, loops and functions.",
    chapters: [
      { n: 9, slug: "lists", title: "Lists: Your First Data Structure",
        summary: "A watchlist, a week of closing prices, a basket of stocks - lists hold an ordered series you can grow, slice and sort.",
        learn: ["Making a list", "Indexing & slicing", "Adding & removing",
          "Slicing a price series", "Sorting & reversing", "Useful list methods"], tags: ["PY", "NSE"] },
      { n: 10, slug: "tuples", title: "Tuples",
        summary: "Fixed little groups of values - an OHLC bar, a row, a pair - that you don't want to change by accident.",
        learn: ["Tuple vs list", "Why immutability helps", "Unpacking values",
          "An OHLC bar as a tuple", "Returning multiple values", "When to use each"], tags: ["PY"] },
      { n: 11, slug: "dictionaries", title: "Dictionaries",
        summary: "Look things up by name, not position. A live quote - symbol, price, volume - is a dictionary, the most useful structure in finance code.",
        learn: ["Key-value pairs", "A quote as a dict", "Getting & setting values",
          "Looping over a dict", "Nested dictionaries", "get() & defaults"], tags: ["PY", "NSE"] },
      { n: 12, slug: "sets", title: "Sets",
        summary: "A bag of unique things. Strip duplicate symbols, test membership instantly, and compare two watchlists with set maths.",
        learn: ["What a set is", "Removing duplicates", "Fast membership tests",
          "Union & intersection", "Two-watchlist overlap", "Set vs list"], tags: ["PY"] },
      { n: 13, slug: "conditionals", title: "Making Decisions: if / elif / else",
        summary: "Teach your code to choose - buy, sell or hold - with conditions and the boolean logic underneath them.",
        learn: ["if / elif / else", "Boolean conditions", "Combining with and / or",
          "A simple buy / sell rule", "Nested conditions", "Guard clauses"], tags: ["PY"] },
      { n: 14, slug: "loops", title: "Loops: for & while",
        summary: "Do something to every price in a series without writing it a hundred times - the heartbeat of all data work.",
        learn: ["The for loop", "Looping over prices", "range() & enumerate",
          "while loops", "break & continue", "Accumulating a total"], tags: ["PY", "NSE"] },
      { n: 15, slug: "comprehensions", title: "Comprehensions",
        summary: "The elegant Python one-liner that builds a new list or dict from an old one - you'll see it everywhere.",
        learn: ["List comprehensions", "Filtering with if", "Transforming prices",
          "Dict comprehensions", "Readability vs cleverness", "Common patterns"], tags: ["PY"] },
      { n: 16, slug: "functions", title: "Functions",
        summary: "Wrap a calculation in a name and reuse it forever. Write 'percentage_change' once, call it a thousand times.",
        learn: ["Defining a function", "Arguments & return", "A reusable P&L function",
          "Default arguments", "Docstrings", "Why functions matter"], tags: ["PY"] },
    ],
  },
  {
    id: "3",
    name: "Libraries, Files & Robust Code",
    desc: "Use other people's code, read and write files, handle dates, and fix errors like a pro.",
    chapters: [
      { n: 17, slug: "modules-and-imports", title: "Modules & Imports",
        summary: "Python comes with batteries included. Learn to import ready-made tools - and split your own code into tidy files.",
        learn: ["What a module is", "import & from-import", "Aliasing with as",
          "The math & statistics modules", "Your own module", "Where Python looks"], tags: ["PY"] },
      { n: 18, slug: "standard-library", title: "The Standard Library Tour",
        summary: "A quick tour of the free toolbox that ships with Python - dates, maths, randomness and JSON, no install needed.",
        learn: ["datetime basics", "math & statistics", "random for simulation",
          "json in & out", "the csv module", "Batteries included"], tags: ["PY"] },
      { n: 19, slug: "installing-libraries", title: "Installing Libraries: pip & venv",
        summary: "Reach beyond the standard library. Install pandas and friends with pip, and keep projects clean with virtual environments.",
        learn: ["pip install", "Finding packages", "Virtual environments",
          "Why venv matters", "requirements.txt", "Installing pandas & yfinance"], tags: ["PY"] },
      { n: 20, slug: "errors-and-debugging", title: "Errors & Debugging",
        summary: "Every coder hits red text. Read a traceback calmly, catch errors with try/except, and fix the usual beginner slips.",
        learn: ["Reading a traceback", "Common error types", "try / except",
          "Raising your own errors", "print-debugging", "A calm debugging mindset"], tags: ["PY"] },
      { n: 21, slug: "files", title: "Reading & Writing Files",
        summary: "Save your results and load data from disk - open files safely, read lines, and write a small report.",
        learn: ["Opening a file", "Reading text", "The with block",
          "Writing & appending", "File paths", "Saving a small report"], tags: ["PY"] },
      { n: 22, slug: "json-data", title: "Working with JSON",
        summary: "JSON is how market APIs talk. Turn a JSON string into a Python dict and back - the format you'll meet again and again.",
        learn: ["What JSON is", "json.loads & dumps", "JSON <-> dict",
          "Nested market data", "Reading a JSON file", "Pretty-printing"], tags: ["PY", "NSE"] },
      { n: 23, slug: "dates-and-times", title: "Dates & Times",
        summary: "Markets run on a clock and a calendar. Parse, format and do arithmetic with dates - sessions, expiries and gaps.",
        learn: ["date & datetime", "Parsing & formatting", "strftime & strptime",
          "timedelta maths", "Market session times", "Weekday & holidays"], tags: ["PY"] },
      { n: 24, slug: "getting-unstuck", title: "Getting Unstuck",
        summary: "The real superpower: helping yourself. Use help(), read the docs, search well, and never be truly stuck again.",
        learn: ["help() & dir()", "Reading documentation", "Searching effectively",
          "Reading error messages", "Minimal examples", "Asking good questions"], tags: ["PY"] },
    ],
  },
  {
    id: "4",
    name: "Data Analysis with NumPy & Pandas",
    desc: "The real workhorses of finance in Python - fast arrays, labelled tables, and charts that communicate.",
    chapters: [
      { n: 25, slug: "numpy-basics", title: "NumPy Basics",
        summary: "The fast array that powers all of data science - and the 30x speed-up over plain Python from Chapter 1, now in your own hands.",
        learn: ["What an array is", "Creating arrays", "Vectorised maths",
          "Array stats (mean, std)", "The 30x speed-up", "Arrays vs lists"], tags: ["PY"] },
      { n: 26, slug: "pandas-series", title: "Pandas Series",
        summary: "A column of numbers with labels - a price series you can do real maths on, and the gateway into pandas.",
        learn: ["What a Series is", "Index & values", "Vectorised operations",
          "Computing returns", "Handy methods", "Series from a list"], tags: ["PY", "US"] },
      { n: 27, slug: "dataframes", title: "The DataFrame",
        summary: "A spreadsheet in Python. The table at the centre of every analysis - rows, columns and the operations you'll use daily.",
        learn: ["What a DataFrame is", "Columns & rows", "Selecting data",
          "Filtering rows", "Adding columns", "Quick inspection"], tags: ["US"] },
      { n: 28, slug: "loading-data", title: "Loading Market Data",
        summary: "Real prices, in two lines. Pull US stocks with yfinance and read a CSV, then look before you leap with head() and info().",
        learn: ["Reading a CSV", "Fetching with yfinance", "head, tail, info",
          "describe()", "Setting an index", "Saving to CSV"], tags: ["US", "NSE"] },
      { n: 29, slug: "data-cleaning", title: "Data Cleaning",
        summary: "Real data is messy. Handle the missing values (yes, the NaN yfinance leaves behind), wrong types and duplicates that quietly ruin results.",
        learn: ["Spotting missing data", "dropna & fillna", "Why NaN appears",
          "Fixing data types", "Removing duplicates", "Sanity checks"], tags: ["NSE"] },
      { n: 30, slug: "dates-in-pandas", title: "Dates & Time Series",
        summary: "Pandas was built for time series. Use a datetime index to resample daily bars to weekly and compute rolling averages.",
        learn: ["The datetime index", "Selecting by date", "Resampling timeframes",
          "Rolling windows", "Shifting for returns", "Time-series gotchas"], tags: ["US"] },
      { n: 31, slug: "grouping-data", title: "Grouping & Aggregation",
        summary: "Answer real questions of your data - average return by month, biggest day per stock - with the group-by pattern.",
        learn: ["Split-apply-combine", "groupby basics", "Aggregating with agg",
          "Grouping by month", "Multiple stocks", "Summary tables"], tags: ["US", "NSE"] },
      { n: 32, slug: "visualization", title: "Data Visualization",
        summary: "A chart is worth a thousand rows. Draw price lines, return histograms and clean seaborn charts that actually communicate.",
        learn: ["matplotlib basics", "Plotting a price line", "Histograms of returns",
          "Styling with seaborn", "Labels & titles", "Saving a figure"], tags: ["US", "NSE"] },
    ],
  },
  {
    id: "5",
    name: "Python for the Markets",
    desc: "Put it all together on real Indian and US market data - OHLCV, live quotes, returns and signals.",
    chapters: [
      { n: 33, slug: "market-landscape", title: "The Market Landscape",
        summary: "A trader's-eye map of where this data comes from - NSE and BSE, US exchanges, indices and the segments you'll meet.",
        learn: ["NSE, BSE & SEBI", "US exchanges", "Cash vs derivatives",
          "Major indices", "Demat & settlement, briefly", "Where data comes from"], tags: ["NSE", "US", "INDEX"] },
      { n: 34, slug: "symbols-and-tickers", title: "Symbols, Tickers & Lot Sizes",
        summary: "RELIANCE, RELIANCE.NS or AAPL? Learn the symbol systems across India and the US, plus lot sizes and what a ticker really is.",
        learn: ["NSE symbols", "Yahoo .NS / .BO suffixes", "US tickers",
          "Index symbols", "Lot size basics", "Mapping symbols across sources"], tags: ["NSE", "US"] },
      { n: 35, slug: "money-timings-holidays", title: "Money, Timings & Holidays",
        summary: "Lakhs vs millions, 9:15 IST vs 9:30 ET - the everyday units and clocks of Indian and US markets, expressed in code.",
        learn: ["Lakh & crore vs million", "Formatting Indian money", "Market hours IST vs ET",
          "Time zones in Python", "Trading holidays", "Sessions & pre-open"], tags: ["NSE", "US"] },
      { n: 36, slug: "ohlcv-data", title: "Working with OHLCV Data",
        summary: "Open, high, low, close, volume - the five numbers behind every candle. Compute the range, body and returns from a real bar.",
        learn: ["What OHLCV means", "A candle, decoded", "Daily range & body",
          "Computing returns", "Up days vs down days", "From bars to insight"], tags: ["NSE", "US"] },
      { n: 37, slug: "fetching-data", title: "Fetching Data over HTTP",
        summary: "How programs talk to markets. Use the requests library to hit OpenAlgo's REST API and read the JSON that comes back - live, from India.",
        learn: ["What an API is", "Request & response", "The requests library",
          "Calling OpenAlgo REST", "Reading the JSON", "Handling errors"], tags: ["NSE", "LIVE"] },
      { n: 38, slug: "quotes-and-live", title: "Live Quotes & Delayed Data",
        summary: "The difference between a live price and yesterday's close - pull live Indian quotes from OpenAlgo and delayed US data from yfinance, side by side.",
        learn: ["Live vs delayed data", "Live LTP from OpenAlgo", "US quotes from yfinance",
          "Why the gap matters", "Quote fields explained", "Building a quote board"], tags: ["NSE", "LIVE", "US"] },
      { n: 39, slug: "websockets-concept", title: "What a WebSocket Is",
        summary: "Why live trading data streams to you instead of being asked for. A plain-words look at WebSockets - the concept, no setup required.",
        learn: ["Request/response vs streaming", "What a WebSocket is", "Why ticks stream",
          "A subscribe message", "When you'd need one", "SDK vs raw socket"], tags: ["LIVE"] },
      { n: 40, slug: "returns-signals-performance", title: "Returns, Signals & Performance",
        summary: "Everything you've learned, on one chart - turn prices into returns, a moving-average crossover into a signal, and judge it with win-rate and drawdown. Then: where to go next.",
        learn: ["Prices to returns", "A moving-average signal", "Crossovers in pandas",
          "Win-rate & average move", "Maximum drawdown", "Where to go from here"], tags: ["US", "NSE"] },
    ],
  },
];

export const CHAPTERS = PARTS.flatMap((p) =>
  p.chapters.map((c) => ({ ...c, part: p.id, partName: p.name })),
).sort((a, b) => a.n - b.n);

export function chapterBySlug(slug) {
  return CHAPTERS.find((c) => c.slug === slug) || null;
}

export const TAG_CLASS = { PY: "py", US: "us", NSE: "nse", INDEX: "idx", LIVE: "live", NFO: "nfo" };
