// Runtime loader for the Options Basics course. Reads pre-rendered chapter
// HTML from a bundled JSON module (generated by scripts/gen-options-basics-content.mjs at
// build time). No filesystem access here, so it works anywhere - including
// Cloudflare Workers where process.cwd() is not the bundle directory.
import data from "./optionsBasicsContentData.json";

const EMPTY = { html: "", toc: [], imgCount: 0, hasContent: false };

export function loadChapter(n) {
  return data[String(n)] || data[n] || EMPTY;
}

export function chapterHasContent(n) {
  return loadChapter(n).hasContent;
}
