// Single source of truth for the "Algo Trading with Python" learning portal:
// 32 chapters across 9 modules. Slugs form the /python/<slug> URLs - keep them stable.

export const SERIES_TITLE = "Algo Trading with Python";
export const SERIES_SUB =
  "A hands-on series for traders new to Python - built entirely on the OpenAlgo Python SDK.";

export const PARTS = [
  {
    id: "A",
    name: "Foundations",
    desc: "Set up, talk to the market, and learn just enough Python, NumPy and Pandas.",
    chapters: [
      { n: 1, slug: "getting-started", title: "Getting Started with OpenAlgo",
        summary: "Connect the OpenAlgo Python SDK, check funds, and understand analyze vs live mode.",
        learn: ["Set up a workspace with uv", "Create an api client", "Keep secrets in .env",
          "Read funds & version", "Analyze mode vs live mode", "Your first data pull"], tags: ["NSE"] },
      { n: 2, slug: "python-for-traders", title: "Python Essentials for Traders",
        summary: "The Python you actually need - variables, lists, dicts, loops and functions, in a trading context.",
        learn: ["Numbers & P&L math", "Lists & dicts of positions", "Loops over symbols",
          "Functions for reusable logic", "Conditionals for signals", "Handling SDK responses"], tags: ["NSE"] },
      { n: 3, slug: "symbols-exchanges", title: "Symbols, Exchanges & Lot Sizes",
        summary: "Master the OpenAlgo symbol format across NSE equity, NFO F&O and MCX commodities.",
        learn: ["Equity / future / option symbols", "search() & symbol()", "Index symbols",
          "expiry() for F&O", "instruments() master list", "Lot sizes for sizing"], tags: ["NSE", "NFO", "MCX", "INDEX"] },
      { n: 4, slug: "market-data-quotes", title: "Quotes, Depth & LTP",
        summary: "Pull live snapshots - single quotes, batched multiquotes and full order-book depth.",
        learn: ["quotes() for one symbol", "multiquotes() for many", "depth() order book",
          "Bid/ask spread", "Quotes across exchanges", "Building a quote board"], tags: ["NSE", "NFO", "MCX"] },
      { n: 5, slug: "historical-data", title: "Historical Data & Timeframes",
        summary: "Fetch OHLCV history at any interval and reshape it for analysis.",
        learn: ["history() OHLCV", "Intervals from 1m to D", "Date ranges",
          "Multi-symbol download", "api vs db source", "Resampling timeframes"], tags: ["NSE", "NFO", "MCX"] },
      { n: 6, slug: "numpy-for-traders", title: "NumPy for Traders",
        summary: "NumPy fundamentals for traders - creating arrays, indexing, vectorised math and the everyday functions, on simple price data.",
        learn: ["Creating arrays & helpers", "Shape, size & dtype", "Indexing & slicing",
          "Vectorised math & broadcasting", "Aggregations, masks & np.where", "2D arrays & the axis argument"], tags: ["NSE", "INDEX"] },
      { n: 7, slug: "pandas-for-traders", title: "Pandas for Traders",
        summary: "DataFrames, rolling windows, resampling and group-bys - the workhorse of market analysis.",
        learn: ["Series & DataFrame on OHLCV", "Indexing & slicing by date", "Rolling windows",
          "Resample to higher TF", "groupby aggregations", "Returns & drawdown"], tags: ["NSE", "MCX"] },
    ],
  },
  {
    id: "B",
    name: "Visualisation & Apps",
    desc: "Turn data into charts and interactive dashboards.",
    chapters: [
      { n: 8, slug: "matplotlib-charts", title: "Charting with Matplotlib",
        summary: "Static charts: price lines, return distributions, subplots and indicator overlays.",
        learn: ["Line & step charts", "Subplots", "Return histograms", "Seaborn statistical charts",
          "Correlation heatmaps", "Save figures to file"], tags: ["NSE", "MCX", "INDEX"] },
      { n: 9, slug: "plotly-charts", title: "Interactive Charts with Plotly",
        summary: "Zoomable candlestick charts with volume and multi-pane indicators.",
        learn: ["Candlestick chart", "Volume sub-pane", "Indicator overlays",
          "RSI/MACD panes", "Range slider", "Export to HTML"], tags: ["NSE", "NFO"] },
      { n: 10, slug: "streamlit-apps", title: "Live Dashboards with Streamlit",
        summary: "Build clickable web apps - a quote board, a chart viewer and a mini scanner.",
        learn: ["Streamlit basics", "Widgets & inputs", "Live quote dashboard",
          "Embed a chart", "A simple scanner UI", "Caching SDK calls"], tags: ["NSE", "MCX"] },
    ],
  },
  {
    id: "C",
    name: "Technical Indicators",
    desc: "Eighty-plus indicators from the openalgo.ta library, by category.",
    chapters: [
      { n: 11, slug: "trend-indicators", title: "Trend & Moving Averages",
        summary: "From SMA and EMA to Supertrend, Ichimoku and Parabolic SAR.",
        learn: ["SMA / EMA / WMA", "HMA / ALMA / KAMA / VWMA", "Supertrend",
          "Ichimoku Cloud", "Parabolic SAR", "Choosing a trend filter"], tags: ["NSE", "NFO", "MCX"] },
      { n: 12, slug: "momentum-indicators", title: "Momentum Indicators",
        summary: "Measure speed and strength: RSI, MACD, Stochastic, CCI and more.",
        learn: ["RSI", "MACD", "Stochastic", "CCI & Williams %R", "Fisher Transform", "Connors RSI"], tags: ["NSE", "NFO"] },
      { n: 13, slug: "volatility-indicators", title: "Volatility Indicators",
        summary: "ATR, Bollinger Bands, Keltner and Donchian channels for range and risk.",
        learn: ["ATR & NATR", "Bollinger Bands", "Keltner Channel", "Donchian Channel",
          "Chandelier Exit", "BB width & %B"], tags: ["NSE", "MCX"] },
      { n: 14, slug: "volume-indicators", title: "Volume Indicators",
        summary: "Read participation with OBV, VWAP, MFI, CMF and relative volume.",
        learn: ["OBV", "VWAP", "Money Flow Index", "Chaikin Money Flow",
          "Accumulation/Distribution", "Relative volume"], tags: ["NSE", "NFO"] },
      { n: 15, slug: "oscillators", title: "Oscillators",
        summary: "Bounded momentum tools: ROC, TRIX, Awesome Oscillator, StochRSI, Vortex and friends.",
        learn: ["ROC & CMO", "TRIX", "Awesome Oscillator", "Stochastic RSI",
          "Vortex & TSI", "Choppiness Index"], tags: ["NSE", "MCX"] },
      { n: 16, slug: "statistical-hybrid", title: "Statistical, Hybrid & Utility Functions",
        summary: "Regression, correlation, ADX, pivots - plus the signal helpers you'll use everywhere.",
        learn: ["Linear regression & slope", "Correlation & beta", "ADX / DMI",
          "Pivot points", "crossover / crossunder", "exrem / flip / valuewhen"], tags: ["NSE", "NFO"] },
    ],
  },
  {
    id: "D",
    name: "Signals & Scanning",
    desc: "Convert indicators into clean signals and screen the whole market.",
    chapters: [
      { n: 17, slug: "signals", title: "From Indicators to Trading Signals",
        summary: "Build precise, de-duplicated entry and exit signals you can trust in a backtest.",
        learn: ["Boolean conditions", "crossover / crossunder", "exrem to remove repeats",
          "flip for stateful holds", "valuewhen lookups", "Shifting to avoid look-ahead"], tags: ["NSE"] },
      { n: 18, slug: "scanning", title: "Scanning & Screeners",
        summary: "Run a signal across dozens of symbols and rank the results.",
        learn: ["Loop a universe", "RSI / EMA screens", "Breakout scan",
          "Relative-volume scan", "Rank & sort hits", "Scan across exchanges"], tags: ["NSE", "NFO", "MCX"] },
    ],
  },
  {
    id: "E",
    name: "Strategy Playbook",
    desc: "Real strategy styles - each one fetched, signalled and explained.",
    chapters: [
      { n: 19, slug: "cash-equity-strategies", title: "Cash & Equity Strategies",
        summary: "Delivery-style trend following and momentum ranking on equities.",
        learn: ["Golden-cross trend", "Momentum ranking", "Donchian breakout",
          "Position vs CNC", "Equity curve preview", "Universe rotation"], tags: ["NSE"] },
      { n: 20, slug: "intraday-strategies", title: "Intraday Strategies",
        summary: "Opening-range breakout, VWAP reversion and intraday EMA systems.",
        learn: ["Opening Range Breakout", "VWAP mean-reversion", "Intraday EMA cross",
          "Time-based exits", "MIS product", "Index & stock futures"], tags: ["NSE", "NFO"] },
      { n: 21, slug: "pair-stat-arb", title: "Pair Trading & Statistical Arbitrage",
        summary: "Trade the spread: ratio, z-score, correlation and beta-neutral pairs.",
        learn: ["Build a price spread", "Z-score of the spread", "Correlation filter",
          "Beta & hedge ratio", "Entry/exit bands", "Stat-arb mechanics"], tags: ["NSE"] },
      { n: 22, slug: "momentum-volatility", title: "Momentum & Volatility Trading",
        summary: "Cross-sectional momentum plus ATR / Bollinger volatility-driven entries and sizing.",
        learn: ["Cross-sectional momentum", "ATR breakout", "Bollinger squeeze",
          "Volatility targeting", "Regime filter", "Vol-scaled position size"], tags: ["NSE", "MCX"] },
      { n: 23, slug: "seasonal-strategies", title: "Seasonal & Calendar Strategies",
        summary: "Day-of-week, month and expiry-week effects measured straight from history.",
        learn: ["Day-of-week returns", "Monthly seasonality", "Turn-of-month effect",
          "Expiry-week behaviour", "Calendar masks in Pandas", "Backtest a seasonal rule"], tags: ["NSE", "NFO"] },
      { n: 24, slug: "options-strategies", title: "Options Strategies",
        summary: "From the option chain to buying, spreads, straddles and hedging - all by symbol.",
        learn: ["Option chain & ATM", "optionsymbol() & greeks", "Buying calls / puts",
          "Vertical & straddle legs", "Hedging a position", "Multi-leg orders"], tags: ["NFO", "INDEX"] },
    ],
  },
  {
    id: "F",
    name: "Execution",
    desc: "Place and manage real orders through the SDK (in analyze mode).",
    chapters: [
      { n: 25, slug: "placing-orders", title: "Placing & Managing Orders",
        summary: "Every order type - market, limit, SL, smart, basket, split - plus modify and cancel.",
        learn: ["placeorder() types", "placesmartorder()", "basket & split orders",
          "modify / cancel", "Order & position books", "Close all positions"], tags: ["NSE", "NFO", "MCX"] },
    ],
  },
  {
    id: "G",
    name: "Backtesting & Optimisation",
    desc: "Prove an edge before risking capital - with VectorBT.",
    chapters: [
      { n: 26, slug: "backtesting-basics", title: "Backtesting from Scratch & with VectorBT",
        summary: "Build a vectorised backtest by hand, then reproduce it with VectorBT and realistic costs.",
        learn: ["Positions from signals", "Returns & equity curve", "Costs & slippage",
          "VectorBT from_signals", "Reading pf.stats()", "Long-only vs both"], tags: ["NSE", "MCX"] },
      { n: 27, slug: "performance-metrics", title: "Performance Metrics & Reporting",
        summary: "Sharpe, Sortino, CAGR, drawdown and win-rate - plus a full QuantStats report.",
        learn: ["CAGR & total return", "Sharpe & Sortino", "Max drawdown",
          "Win rate & profit factor", "Benchmark vs index", "QuantStats tearsheet"], tags: ["NSE"] },
      { n: 28, slug: "optimization", title: "Parameter Optimisation",
        summary: "Sweep parameter grids, draw heatmaps and pick robust settings - not just the best.",
        learn: ["Define a param grid", "VectorBT broadcasting", "Returns heatmap",
          "Sharpe heatmap", "Robust vs peak", "Cost-aware optimisation"], tags: ["NSE", "MCX"] },
      { n: 29, slug: "walk-forward", title: "Walk-Forward Testing & Robustness",
        summary: "Split in- and out-of-sample, roll the window forward, and avoid fooling yourself.",
        learn: ["Train/test split", "In- vs out-of-sample", "Rolling walk-forward",
          "Parameter stability", "Overfitting red flags", "Deflated expectations"], tags: ["NSE"] },
    ],
  },
  {
    id: "H",
    name: "Machine Learning",
    desc: "Teach a model to read the market, then ship a complete bot.",
    chapters: [
      { n: 30, slug: "ml-neural-capstone", title: "Machine Learning, Neural Nets & a Complete Bot",
        summary: "Engineer features, train a classifier and a neural network, then wire it into a live OpenAlgo loop.",
        learn: ["Features from indicators", "Train/test for ML", "Logistic & random forest",
          "A neural network (MLP)", "Walk-forward ML check", "End-to-end trading bot"], tags: ["NSE", "NFO"] },
    ],
  },
  {
    id: "I",
    name: "Going Live",
    desc: "Stream live ticks over WebSockets and manage real positions in real time.",
    chapters: [
      { n: 31, slug: "websockets", title: "Real-Time Data with WebSockets",
        summary: "Stream live ticks over a WebSocket and manage a position in real time - computing stop-loss, target and trailing stop as each price arrives.",
        learn: ["Polling (REST) vs streaming (WebSocket)", "When to use the API vs the feed",
          "connect() & subscribe_ltp/quote/depth", "Compute a live stop-loss & target",
          "Trailing stop-loss on every tick", "A complete live trade manager"], tags: ["NSE", "NFO", "MCX"] },
      { n: 32, slug: "risk-position-sizing", title: "Risk & Position Sizing",
        summary: "Turn a signal into the right quantity - sizing by fixed-fractional risk, the stop distance, ATR and portfolio heat, with a reusable lot-aware sizer.",
        learn: ["Why sizing beats entries", "Fixed-fractional: risk 1% per trade",
          "Quantity from the stop distance", "ATR-based stops & volatility sizing",
          "Portfolio heat & exposure caps", "A reusable position_size() helper"], tags: ["NSE", "NFO", "MCX"] },
    ],
  },
];

export const CHAPTERS = PARTS.flatMap((p) =>
  p.chapters.map((c) => ({ ...c, part: p.id, partName: p.name }))
).sort((a, b) => a.n - b.n);

export function chapterBySlug(slug) {
  return CHAPTERS.find((c) => c.slug === slug) || null;
}

export const TAG_CLASS = { NSE: "nse", NFO: "nfo", MCX: "mcx", INDEX: "idx", BSE: "nse", CDS: "idx" };
