// Single source of truth for the "Quantitative Trading" learning portal:
// 78 chapters across 9 modules, a full Indian-market quant career curriculum -
// career map and market structure, quant math, microstructure, HFT and execution
// technology, time series, derivatives, alpha research, backtesting and ML, and
// production. Taught Zerodha-Varsity style at an expert-but-readable level, every
// example run on real OpenAlgo data. Slugs form the /quant/<slug> URLs - keep them
// stable.

export const SERIES_TITLE = "Quantitative Trading";
export const SERIES_SUB =
  "A complete, India-focused path from trader to working quant - the market's plumbing, its mathematics, its microstructure and the technology of speed, then derivatives, alpha research, honest backtesting and production, all grounded in real Indian market data through the OpenAlgo SDK.";

export const PARTS = [
  {
    id: "A",
    name: "Quant Career Map & Indian Market Structure",
    desc: "What a quant really does, the firms and roles, and exactly how the Indian market is wired.",
    chapters: [
      { n: 1, slug: "what-is-a-quant", title: "What a Quant Actually Does",
        summary: "The real job behind the word - how a quant turns a market question into a tested, sized, monitored decision, and how that differs from discretionary trading.",
        learn: ["Quant vs discretionary thinking", "The research-to-risk loop", "Signal vs noise", "The quant skill stack", "What a day actually looks like", "Myths vs reality"], tags: ["NSE", "INDEX"] },
      { n: 2, slug: "quant-roles", title: "Quant Researcher vs Quant Trader vs Quant Developer",
        summary: "The three core quant roles, the skills each demands, and how research, trading and engineering hand work to each other on a real desk.",
        learn: ["Researcher / trader / developer", "Skill ladders for each", "How the roles collaborate", "Execution quant vs alpha quant", "Where you fit", "Building toward a role"], tags: ["NSE"] },
      { n: 3, slug: "quant-firms", title: "Buy-Side, Sell-Side, Prop and HFT Firms",
        summary: "The firm landscape a quant works in - banks, brokers, mutual funds, hedge funds, prop shops and HFT houses - and how their incentives shape the work.",
        learn: ["Buy-side vs sell-side", "Prop trading firms", "HFT and market-making houses", "AMCs, PMS and AIFs in India", "How incentives shape strategy", "Who hires quants in India"], tags: ["NSE"] },
      { n: 4, slug: "indian-market-map", title: "The Map of Indian Markets",
        summary: "NSE and BSE, cash, F&O, currency and debt segments, the headline indices, and the segments a quant actually trades.",
        learn: ["NSE vs BSE", "Cash, F&O, currency, debt segments", "Nifty, Bank Nifty, FinNifty, Sensex", "Lot sizes and contract types", "Index vs single-stock", "Which segment for which edge"], tags: ["NSE", "INDEX"] },
      { n: 5, slug: "market-participants", title: "Market Participants and Who Moves Prices",
        summary: "Retail, HNI, FPI, DII, proprietary desks and market makers - who supplies and who demands liquidity, and how to read their footprints in the data.",
        learn: ["Retail and HNI flow", "FPI and DII behaviour", "Proprietary desks", "Market makers and liquidity providers", "Informed vs uninformed flow", "Reading participant data"], tags: ["NSE", "NFO"] },
      { n: 6, slug: "market-plumbing", title: "SEBI, Exchanges, Clearing Corps and Depositories",
        summary: "The institutional plumbing - the regulator, the exchanges, the clearing corporations with their default waterfall, the depositories, and interoperability.",
        learn: ["SEBI's mandate", "Exchanges vs clearing corporations", "The CCP and default waterfall", "NSDL and CDSL depositories", "Clearing interoperability", "Why the plumbing matters to a quant"], tags: ["NSE"] },
      { n: 7, slug: "clearing-and-settlement", title: "Clearing, Settlement, T+1 and Optional T+0",
        summary: "The life of a trade after the match - novation, netting, margins through the day, the T+1 cycle and India's optional T+0 settlement.",
        learn: ["Trade life cycle after matching", "Novation and netting", "Settlement obligations", "The T+1 cycle", "Optional T+0 settlement", "Settlement risk and a quant"], tags: ["NSE"] },
      { n: 8, slug: "cost-of-trading", title: "The True Cost of a Trade",
        summary: "STT, stamp duty, exchange and SEBI charges, GST and brokerage, plus spread, slippage and impact - the all-in cost model that quietly kills most edges.",
        learn: ["STT by segment", "Stamp duty and exchange charges", "SEBI fees and GST", "Brokerage and DP charges", "Spread, slippage and impact", "An all-in cost function"], tags: ["NSE", "NFO"] },
    ],
  },
  {
    id: "B",
    name: "Quant Math, Statistics & Research Foundations",
    desc: "Probability, statistics and linear algebra for trading - in plain words, with charts and real returns.",
    chapters: [
      { n: 9, slug: "returns-and-distributions", title: "Returns, Log Returns and Stylized Facts",
        summary: "Simple vs log returns and the empirical truths of markets - fat tails, volatility clustering and the leverage effect, measured on real Indian data.",
        learn: ["Simple vs log returns", "Compounding and aggregation", "Fat tails vs the bell curve", "Volatility clustering", "The leverage effect", "Stylized facts on Nifty"], tags: ["NSE", "INDEX"] },
      { n: 10, slug: "probability-for-traders", title: "Probability for Traders",
        summary: "Random variables, expectation and variance, conditional probability and Bayes - the probability a trader actually uses, built from market examples.",
        learn: ["Random variables and expectation", "Variance and standard deviation", "Conditional probability", "Bayes for traders", "Law of large numbers", "Monte Carlo simulation"], tags: ["INDEX"] },
      { n: 11, slug: "distributions-fat-tails", title: "Distributions, Fat Tails and Extreme Moves",
        summary: "Why the normal distribution understates risk - kurtosis, the Student-t, power laws and extreme-value thinking applied to Indian market crashes.",
        learn: ["The normal and its failures", "Skewness and kurtosis", "Student-t and stable laws", "Power laws in returns", "Extreme value theory", "Sizing for fat tails"], tags: ["NSE", "INDEX"] },
      { n: 12, slug: "inference-and-hypothesis-testing", title: "Statistical Inference and Hypothesis Testing",
        summary: "Sampling, estimation, confidence intervals and hypothesis tests - the honest machinery for asking whether an edge is really there.",
        learn: ["Sampling and estimates", "Confidence intervals", "Hypothesis testing", "p-values, honestly", "t-tests and bootstrap", "Effect size vs significance"], tags: ["NSE"] },
      { n: 13, slug: "multiple-testing", title: "Multiple Testing and False Discovery",
        summary: "Test 500 ideas and a fake winner is almost guaranteed - the multiple-comparisons problem, family-wise error, false discovery rate and the deflated Sharpe.",
        learn: ["The multiple-testing trap", "Family-wise error rate", "Bonferroni and Holm", "False discovery rate", "Data snooping in backtests", "The deflated Sharpe ratio"], tags: ["NSE"] },
      { n: 14, slug: "stationarity-random-walk", title: "Stationarity, Random Walks and the EMH",
        summary: "Why prices wander unpredictably, how to test for it, and what the efficient-market idea gets right and wrong.",
        learn: ["The random walk", "Stationary vs non-stationary", "ADF and KPSS tests", "Why prices resist prediction", "The efficient market hypothesis", "Where the EMH cracks"], tags: ["NSE", "INDEX"] },
      { n: 15, slug: "linear-algebra-pca", title: "Linear Algebra, Covariance and PCA",
        summary: "Vectors, matrices and the covariance matrix that sits under every risk model - and how principal components reveal the few factors driving a whole universe.",
        learn: ["Vectors and matrices for quants", "The covariance matrix", "Eigenvalues and eigenvectors", "Principal component analysis", "Factors from PCA on Nifty stocks", "Dimensionality and noise"], tags: ["NSE"] },
      { n: 16, slug: "optimization-methods", title: "Optimization, Constraints and Numerical Methods",
        summary: "How a quant actually solves for weights, parameters and fits - convexity, gradients, constraints and the numerical traps in between.",
        learn: ["Objective functions", "Convex vs non-convex", "Gradient and Newton methods", "Constrained optimisation", "Quadratic programming for portfolios", "Numerical stability traps"], tags: ["NSE", "INDEX"] },
    ],
  },
  {
    id: "C",
    name: "Indian Market Microstructure",
    desc: "How prices are really formed - the order book, the trading day, liquidity, impact and order flow.",
    chapters: [
      { n: 17, slug: "why-microstructure-matters", title: "Why Market Microstructure Matters",
        summary: "The gap between the price on a chart and the price you actually get - and why microstructure is where most retail edges quietly die.",
        learn: ["What microstructure studies", "Quoted vs effective price", "Where edges leak", "The cost of crossing the spread", "Microstructure for slow traders too", "A map of Module C"], tags: ["NSE"] },
      { n: 18, slug: "limit-order-book", title: "Limit Order Book Fundamentals",
        summary: "Bids, asks and depth - the live queue where every Indian trade is matched, read straight from real depth data.",
        learn: ["Bids, asks and depth", "Market vs limit orders", "Reading the depth ladder", "Total buy vs sell quantity", "Disclosed and iceberg quantity", "Reading depth() data"], tags: ["NSE", "MCX"] },
      { n: 19, slug: "order-types-lifecycle", title: "Order Types and the Order Lifecycle",
        summary: "Every order type on Indian exchanges and the full life of an order - entry, modification, cancellation, the audit trail and client-code controls.",
        learn: ["Market, limit, SL and SL-M", "IOC, GTT and iceberg", "Order entry and modification", "Cancellation and the audit trail", "UCC and client-code controls", "Product types (MIS, NRML, CNC)"], tags: ["NSE"] },
      { n: 20, slug: "price-time-priority", title: "Price-Time Priority and Queue Position",
        summary: "How the matching engine decides who fills first, why your place in the queue is worth money, and how queue position drives passive trading.",
        learn: ["Price-time priority", "Queue position and value", "Order book events", "Cancel and replace costs", "Pro-rata vs FIFO matching", "Queue dynamics for quants"], tags: ["NSE", "NFO"] },
      { n: 21, slug: "trading-day-structure", title: "The Indian Trading Day Structure",
        summary: "From the pre-open to the post-close - every session of the NSE and BSE day, the timings and the special segments a quant must respect.",
        learn: ["Pre-open session", "Continuous trading", "Block and bulk windows", "Closing session and post-close", "Special pre-open for new listings", "Commodity and currency hours"], tags: ["NSE", "MCX", "CDS"] },
      { n: 22, slug: "auctions", title: "Pre-Open, Call Auction and Closing Auction",
        summary: "How call auctions discover one clean price from a book of orders - the pre-open mechanism and SEBI's new closing auction session.",
        learn: ["Call auction mechanics", "Equilibrium price discovery", "The pre-open auction", "Order imbalance signals", "The closing auction session (CAS)", "Auction vs continuous trading"], tags: ["NSE", "INDEX"] },
      { n: 23, slug: "circuit-breakers", title: "Circuit Breakers, Price Bands and Trading Halts",
        summary: "Index halts, scrip price bands, ASM and GSM lists and the F&O ban - the rules that freeze the market and distort the signals you compute.",
        learn: ["Index circuit breakers", "Scrip price bands", "ASM and GSM lists", "The F&O ban period", "Upper and lower circuits", "Halts and your signals"], tags: ["NSE"] },
      { n: 24, slug: "bulk-block-deals", title: "Bulk Deals, Block Deals and Special Windows",
        summary: "How large players move size without wrecking the price - the bulk-deal and block-deal windows, disclosure rules, and what the prints tell a quant.",
        learn: ["Bulk vs block deals", "The block-deal windows", "Disclosure thresholds", "Reading bulk-deal data", "Negotiated trades", "What large prints signal"], tags: ["NSE"] },
      { n: 25, slug: "liquidity-spread-depth", title: "Liquidity, Spread and Depth",
        summary: "What liquidity really means - quoted and effective spread, depth and resilience, and how to measure them in real NSE names.",
        learn: ["Bid-ask spread components", "Quoted vs effective spread", "Depth and resilience", "Amihud illiquidity", "Measuring liquidity in NSE names", "Liquidity as a cost"], tags: ["NSE"] },
      { n: 26, slug: "impact-cost-tca", title: "Impact Cost, Slippage and Transaction Cost Analysis",
        summary: "Why your own order moves the price - modelling market impact, measuring slippage against benchmarks, and doing honest transaction cost analysis.",
        learn: ["Temporary vs permanent impact", "Kyle's lambda intuition", "Slippage vs arrival price", "Implementation shortfall", "Square-root impact models", "TCA on real fills"], tags: ["NSE"] },
      { n: 27, slug: "order-flow", title: "Open Interest, Volume and Order Flow",
        summary: "Reading pressure in the tape - volume, open interest, participant-wise positions and the order-flow signals that hint at informed activity.",
        learn: ["Volume vs open interest", "Participant-wise OI", "FII/DII flow data", "Order-flow imbalance", "Toxicity and adverse selection", "Flow as a signal"], tags: ["NSE", "NFO"] },
      { n: 28, slug: "short-selling-slb", title: "Short Selling, SLB and Borrowing Mechanics",
        summary: "How shorting really works in India - intraday vs delivery shorts, the securities lending and borrowing market, and the cost and risk of being short.",
        learn: ["Intraday vs delivery shorts", "SLB mechanics", "Borrow cost and availability", "Short squeezes", "Naked short rules in India", "Shorting for market-neutral books"], tags: ["NSE", "NFO"] },
    ],
  },
  {
    id: "D",
    name: "HFT, Execution & Trading Technology",
    desc: "Algorithmic trading, the speed game, execution algorithms and the technology and rules that govern them.",
    chapters: [
      { n: 29, slug: "algo-trading-foundations", title: "Algorithmic Trading Foundations",
        summary: "What an algorithmic strategy actually is - the loop from data to signal to order to risk, and the architecture every automated system shares.",
        learn: ["The algo trading loop", "Signal, sizing and execution layers", "Event-driven vs polling", "State and idempotency", "OpenAlgo as an order gateway", "From idea to running bot"], tags: ["NSE"] },
      { n: 30, slug: "hft-vs-algo-vs-systematic", title: "HFT vs Algo Trading vs Systematic Trading",
        summary: "Three words people confuse - the latency, holding period and infrastructure that separate true HFT from algorithmic and systematic trading.",
        learn: ["Defining HFT", "Algo vs systematic", "Latency and holding periods", "Who can play at each level", "Infrastructure by tier", "Where retail quants fit"], tags: ["NSE"] },
      { n: 31, slug: "dma-colocation-latency", title: "DMA, Co-Location and Low-Latency Access",
        summary: "The microstructure of speed - direct market access, co-location at NSE, tick-by-tick feeds, timestamping and the latency arms race.",
        learn: ["Direct market access", "Co-location at NSE/BSE", "Tick-by-tick data", "Latency arbitrage", "Timestamping and clocks", "Where retail can and cannot play"], tags: ["NSE"] },
      { n: 32, slug: "market-data-feeds", title: "Market Data Feeds: Snapshot, Tick, L2 and L3",
        summary: "The data behind every algo - snapshot vs tick feeds, the L1, L2 and L3 levels of the book, broadcast vs unicast, and what each costs and reveals.",
        learn: ["Snapshot vs tick feeds", "L1, L2 and L3 data", "Exchange broadcast feeds", "Conflated vs full depth", "Feed handlers and gaps", "Choosing the right feed"], tags: ["NSE", "MCX"] },
      { n: 33, slug: "orderbook-reconstruction", title: "Order Book Reconstruction and Replay",
        summary: "Rebuilding the full limit order book from a feed of events, replaying a trading day deterministically, and using it to test execution.",
        learn: ["From events to a book", "Add, modify, cancel, trade", "Deterministic replay", "Reconstruction pitfalls", "Building a research dataset", "Replay for execution testing"], tags: ["NSE"] },
      { n: 34, slug: "hft-strategy-families", title: "HFT Strategy Families: Making, Arb and Event",
        summary: "What high-frequency desks actually run - passive market making, latency and statistical arbitrage, and event-driven reaction strategies.",
        learn: ["Passive market making", "Latency arbitrage", "Statistical arbitrage at speed", "Event and news reaction", "Liquidity detection", "Risk in HFT books"], tags: ["NSE", "NFO"] },
      { n: 35, slug: "order-to-trade-ratio", title: "Order-to-Trade Ratio, Cancellations and Quote Stuffing",
        summary: "The exchange's brakes on speed - the order-to-trade ratio, cancellation penalties, and the line between legitimate quoting and manipulative quote stuffing.",
        learn: ["The order-to-trade ratio", "OTR penalties on NSE", "Cancellation economics", "Quote stuffing and spoofing", "Layering and surveillance", "Staying on the right side"], tags: ["NSE"] },
      { n: 36, slug: "smart-order-routing", title: "Smart Order Routing and Multi-Venue Execution",
        summary: "Splitting an order across NSE and BSE for the best fill - smart order routing, the consolidated book, and best execution across venues.",
        learn: ["Why route across venues", "Smart order routing logic", "The consolidated order book", "Best execution duty", "Latency in routing", "SOR for retail via brokers"], tags: ["NSE"] },
      { n: 37, slug: "execution-algorithms", title: "Execution Algorithms: VWAP, TWAP, POV and IS",
        summary: "How big orders are worked into the market without moving it - the scheduling algorithms and the implementation-shortfall framework behind them.",
        learn: ["Why slice large orders", "VWAP and TWAP", "Percentage of volume (POV)", "Implementation shortfall", "Almgren-Chriss intuition", "Choosing an execution algo"], tags: ["NSE"] },
      { n: 38, slug: "market-making-inventory", title: "Market Making and Inventory Risk",
        summary: "The other side of every trade - quoting both sides, earning the spread, and the inventory and adverse-selection risk that can wipe it out.",
        learn: ["Quoting both sides", "Earning the spread", "Inventory risk", "Adverse selection", "Avellaneda-Stoikov intuition", "Skewing quotes to manage inventory"], tags: ["NSE", "NFO"] },
      { n: 39, slug: "retail-api-algo-framework", title: "The Retail API Algo Framework in India",
        summary: "SEBI's framework for safer retail algo trading - API keys, static IP, unique algo IDs, white-box vs black-box classification and the broker and exchange responsibilities.",
        learn: ["SEBI retail algo circular (2025)", "API keys and static IP", "Unique algo ID registration", "White-box vs black-box algos", "Broker and exchange duties", "What changes for retail quants"], tags: ["NSE"] },
      { n: 40, slug: "kill-switches-risk-controls", title: "Kill Switches, Risk Controls and Algo Surveillance",
        summary: "The safety layer every automated trader needs - pre-trade risk checks, position and loss limits, the kill switch and the surveillance that watches for runaways.",
        learn: ["Pre-trade risk checks", "Position and loss limits", "The kill switch", "Throttles and rate limits", "Exchange-level surveillance", "Designing fail-safe systems"], tags: ["NSE"] },
    ],
  },
  {
    id: "E",
    name: "Time Series, Econometrics & Forecasting",
    desc: "Modelling how today's market depends on yesterday's - mean reversion, volatility, regimes and decay.",
    chapters: [
      { n: 41, slug: "time-series-models", title: "AR, MA and ARIMA Models",
        summary: "The classic models for series that remember their past - and an honest look at what is and is not forecastable in returns.",
        learn: ["Autoregression (AR)", "Moving average (MA)", "ARIMA", "Fitting with statsmodels", "Forecasting returns vs vol", "What is truly predictable"], tags: ["NSE", "INDEX"] },
      { n: 42, slug: "volatility-modeling", title: "Volatility Modeling: EWMA, ARCH and GARCH",
        summary: "Volatility has a memory - calm follows calm, storms cluster. EWMA, ARCH and GARCH make that precise on Indian index data.",
        learn: ["Why vol clusters", "EWMA volatility", "ARCH and GARCH intuition", "Fitting GARCH with arch", "Volatility forecasting", "Forecasting Nifty volatility"], tags: ["INDEX"] },
      { n: 43, slug: "realized-volatility", title: "Realized and Intraday Volatility",
        summary: "Measuring volatility from high-frequency data - realized variance, the intraday volatility smile of the trading day, and overnight vs intraday risk.",
        learn: ["Realized variance", "Sampling frequency and noise", "The intraday vol U-shape", "Overnight vs intraday risk", "Realized vs implied", "Using RV in models"], tags: ["INDEX", "NSE"] },
      { n: 44, slug: "mean-reversion-ou", title: "Mean Reversion and Ornstein-Uhlenbeck",
        summary: "The mathematics of a price on a leash - the Ornstein-Uhlenbeck process, the half-life of reversion, and how to test whether a series truly reverts.",
        learn: ["Mean reversion intuition", "The Ornstein-Uhlenbeck process", "Estimating speed of reversion", "Half-life of reversion", "Testing for mean reversion", "Trading a reverting series"], tags: ["NSE"] },
      { n: 45, slug: "cointegration-pairs", title: "Cointegration and Pairs Trading",
        summary: "Two wandering prices tied by a long-run relationship - cointegration, the Engle-Granger test, the spread and z-score, and a full Indian pairs trade.",
        learn: ["Cointegration vs correlation", "Engle-Granger test", "Building the spread", "The z-score signal", "Selecting Indian pairs", "Risks of pairs trading"], tags: ["NSE"] },
      { n: 46, slug: "regimes-and-breaks", title: "Regime Detection and Structural Breaks",
        summary: "Markets switch between calm bulls, grinding bears and violent shocks - detecting the regime you are in and the breaks that end a strategy.",
        learn: ["Bull / bear / sideways regimes", "Volatility regimes", "Markov switching intuition", "Change-point detection", "Structural breaks", "Why a strategy stops working"], tags: ["INDEX"] },
      { n: 47, slug: "forecast-evaluation", title: "Forecast Evaluation and Model Decay",
        summary: "How to judge a forecast honestly and catch a model rotting in real time - error metrics, out-of-sample discipline and decay monitoring.",
        learn: ["Error metrics (MSE, MAE)", "Directional accuracy", "Out-of-sample evaluation", "Diebold-Mariano intuition", "Detecting model decay", "When to retire a model"], tags: ["NSE", "INDEX"] },
      { n: 48, slug: "capacity-and-half-life", title: "Capacity, Turnover and Signal Half-Life",
        summary: "How much money a strategy can hold and how fast its edge fades - capacity from impact, turnover and cost, and the half-life of a signal.",
        learn: ["Strategy capacity", "Turnover and cost drag", "Signal half-life", "Capacity from market impact", "Crowding and decay", "Sizing to capacity"], tags: ["NSE"] },
    ],
  },
  {
    id: "F",
    name: "Derivatives, Volatility & Arbitrage",
    desc: "The derivatives machine in India - futures and basis, options pricing and Greeks, the vol surface, and the arbitrage that ties it together.",
    chapters: [
      { n: 49, slug: "futures-and-carry", title: "Futures, Forwards and Cost of Carry",
        summary: "The most powerful idea in pricing - no free money - and how cost of carry sets the fair price of a future against its underlying.",
        learn: ["Forwards vs futures", "The no-arbitrage principle", "Cost of carry", "Fair value and basis", "Convergence at expiry", "Carry in Indian futures"], tags: ["NFO", "INDEX"] },
      { n: 50, slug: "basis-and-index-arb", title: "Cash-Futures Basis and Index Arbitrage",
        summary: "The arbitrage that runs on every Indian desk - the cash-futures basis, when it is rich or cheap, and how index arbitrage keeps the future honest.",
        learn: ["The cash-futures basis", "Rich vs cheap basis", "Index arbitrage mechanics", "Replicating the index", "Dividends and the basis", "Risks of basis trades"], tags: ["NFO", "INDEX"] },
      { n: 51, slug: "options-pricing", title: "Options Pricing: Black-Scholes vs Black-76",
        summary: "Why Indian F&O is priced with Black-76 off the synthetic future, not Black-Scholes off spot - the models, their assumptions and where they break.",
        learn: ["Put-call parity", "The synthetic future", "Black-Scholes assumptions", "Black-76 off the forward", "Why India uses Black-76", "Pricing a Nifty option"], tags: ["NFO", "INDEX"] },
      { n: 52, slug: "the-greeks", title: "The Greeks: Delta, Gamma, Vega, Theta and Rho",
        summary: "How an option breathes - the Greeks that measure its sensitivity to price, volatility and time, computed live on real Nifty options.",
        learn: ["Delta and gamma", "Vega and theta", "Rho and dividends", "Greeks across strikes", "Position Greeks", "OpenAlgo Greeks on a Nifty option"], tags: ["NFO", "INDEX"] },
      { n: 53, slug: "volatility-surface", title: "The Volatility Surface, Skew and Term Structure",
        summary: "Implied volatility is not one number - the smile and skew across strikes and the term structure across expiries, read off real option chains.",
        learn: ["Implied volatility", "The volatility smile and skew", "Term structure", "Building the surface", "Weekly-expiry dynamics", "Reading the surface"], tags: ["NFO", "INDEX"] },
      { n: 54, slug: "vix-and-vrp", title: "India VIX and the Volatility Risk Premium",
        summary: "The market's fear gauge and the premium for selling insurance - how India VIX is built, what it predicts, and the volatility risk premium.",
        learn: ["How India VIX is computed", "VIX as expected move", "Implied vs realized gap", "The volatility risk premium", "VIX and the index", "Trading the premium"], tags: ["NFO", "INDEX"] },
      { n: 55, slug: "gamma-scalping-vol-trading", title: "Gamma Scalping and Volatility Trading",
        summary: "Volatility as an asset you can trade - delta-hedged straddles, gamma scalping, variance and the Indian expiry-day effects that drive it.",
        learn: ["Volatility as an asset", "Delta-hedged options", "Gamma scalping P&L", "Variance and straddles", "Expiry-day effects", "Selling vs buying vol"], tags: ["NFO", "INDEX"] },
      { n: 56, slug: "equity-derivatives-microstructure", title: "Equity Derivatives Microstructure in India",
        summary: "How index and single-stock F&O actually trade - liquidity across strikes and expiries, weekly vs monthly, and the microstructure quirks of Indian options.",
        learn: ["Index vs stock F&O liquidity", "Weekly vs monthly expiries", "Strike liquidity and spreads", "Expiry concentration", "Physical settlement of stock F&O", "Microstructure quirks"], tags: ["NFO"] },
      { n: 57, slug: "currency-and-rate-derivatives", title: "Currency and Interest-Rate Derivatives",
        summary: "Beyond equities - USD-INR and cross-currency futures and options, interest-rate futures, and how a quant uses them for macro and hedging.",
        learn: ["Currency futures and options", "USD-INR microstructure", "Interest-rate futures (IRF)", "The yield curve basics", "Macro hedging uses", "Liquidity and limits"], tags: ["CDS", "NSE"] },
      { n: 58, slug: "margins-and-position-limits", title: "Margins, Collateral, Position Limits and Settlement",
        summary: "The capital machinery of derivatives - SPAN and exposure margin, collateral and haircuts, position limits, and physical settlement of stock F&O.",
        learn: ["SPAN and exposure margin", "Collateral and haircuts", "Cross-margin benefits", "Position limits", "Physical settlement", "Margin in a quant book"], tags: ["NFO"] },
    ],
  },
  {
    id: "G",
    name: "Alpha Research & Strategy Families",
    desc: "The research process and the major systematic strategy families, built and tested on Indian data.",
    chapters: [
      { n: 59, slug: "alpha-research-process", title: "The Alpha Research Process",
        summary: "Turning a hunch into a tested edge - hypothesis, data, test and validation: the scientific method for trading, with a reusable checklist.",
        learn: ["Idea to hypothesis", "Designing a fair test", "Signal vs noise", "In-sample vs out-of-sample", "Decay and capacity", "A research checklist"], tags: ["NSE"] },
      { n: 60, slug: "cross-sectional-momentum", title: "Cross-Sectional Momentum",
        summary: "The workhorse of systematic equity - rank the universe by past return, go long the winners and short the losers, and account for the Indian frictions.",
        learn: ["Cross-sectional vs time-series", "Formation and holding periods", "Ranking the NSE universe", "Long-short construction", "Momentum crashes", "Costs and turnover"], tags: ["NSE"] },
      { n: 61, slug: "value-quality-factors", title: "Value, Quality, Size and Low-Vol Factors",
        summary: "The handful of forces that drive most equity returns - value, quality, size and low-volatility, built and combined for the Indian market.",
        learn: ["CAPM and beta", "Value and quality factors", "Size and low-vol", "Building India factors", "Combining factors", "The factor zoo and caution"], tags: ["NSE"] },
      { n: 62, slug: "statistical-arbitrage", title: "Statistical Arbitrage and Market-Neutral Books",
        summary: "Market-neutral trading of relationships - pairs and baskets, the cash-futures arb, and building a book with little net market exposure.",
        learn: ["Pairs from cointegration", "Building the spread", "Z-score entries and exits", "Basket and index arb", "Market-neutral construction", "Neutral-book risk"], tags: ["NSE", "NFO"] },
      { n: 63, slug: "event-driven", title: "Event-Driven Strategies",
        summary: "Trading the calendar - earnings drift, index reconstitution, corporate actions and the predictable flows around scheduled events.",
        learn: ["Earnings drift", "Nifty index reconstitution", "Corporate actions", "Buybacks and dividends", "Designing event trades", "Event risk control"], tags: ["NSE", "NFO"] },
      { n: 64, slug: "flow-based-strategies", title: "Flow-Based Strategies: FII/DII, OI and Expiry",
        summary: "Trading the footprints of big money - FII and DII flows, open-interest shifts, the F&O ban list and the powerful Indian expiry-day effects.",
        learn: ["FII/DII flow signals", "Open-interest build-up", "The F&O ban as a signal", "Expiry-day effects", "Rollover analysis", "Combining flow signals"], tags: ["NSE", "NFO"] },
      { n: 65, slug: "intraday-mean-reversion-breakout", title: "Intraday Mean Reversion and Breakout Models",
        summary: "The two intraday archetypes - fading stretched moves and riding confirmed breakouts - built with real intraday data and honest costs.",
        learn: ["Intraday mean reversion", "Opening-range breakout", "VWAP reversion", "Time-of-day effects", "Stops and targets", "Intraday cost reality"], tags: ["NSE", "INDEX"] },
      { n: 66, slug: "alt-data-nlp", title: "Alternative Data and NLP for Indian Markets",
        summary: "Edges beyond price - news, announcements, filings and sentiment, and the natural-language tools that turn text into a tradeable signal.",
        learn: ["What counts as alt data", "News and announcements", "NLP and sentiment", "Filings and disclosures", "Pitfalls of alt data", "Building a text signal"], tags: ["NSE"] },
    ],
  },
  {
    id: "H",
    name: "Backtesting, ML & Portfolio Construction",
    desc: "Testing honestly, using machine learning safely, and turning many signals into one risk-managed book.",
    chapters: [
      { n: 67, slug: "backtesting-rigor", title: "Backtesting Without Fooling Yourself",
        summary: "The traps that turn a losing system into a beautiful backtest, and the discipline that keeps a test honest.",
        learn: ["Anatomy of a backtest", "Realistic fills and costs", "In-sample vs out-of-sample", "Overfitting and snooping", "Sanity checks", "A backtest you can trust"], tags: ["NSE"] },
      { n: 68, slug: "bias-lookahead-survivorship", title: "Look-Ahead, Survivorship and Corporate-Action Bias",
        summary: "The three biases that silently inflate every naive backtest - using the future, ignoring the dead, and mishandling splits and bonuses.",
        learn: ["Look-ahead bias", "Survivorship bias", "Corporate-action adjustment", "Point-in-time data", "Index reconstitution bias", "Auditing a dataset"], tags: ["NSE"] },
      { n: 69, slug: "walkforward-purged-cv", title: "Walk-Forward, Purged CV and Deflated Sharpe",
        summary: "Validation that respects time - walk-forward testing, purged and embargoed cross-validation, and deflating the Sharpe for all the trials you ran.",
        learn: ["Walk-forward testing", "Why ordinary CV leaks", "Purged k-fold CV", "Embargoing", "Combinatorial purged CV", "The deflated Sharpe"], tags: ["NSE"] },
      { n: 70, slug: "ml-in-quant", title: "Machine Learning in Quant: Promise and Peril",
        summary: "Where machine learning genuinely helps a quant, where it quietly leaks the future, and how to use it without fooling yourself.",
        learn: ["Where ML helps vs hurts", "Train/test on time series", "Feature and label leakage", "Tree models vs linear", "Feature importance", "Avoiding overfit ML"], tags: ["NSE"] },
      { n: 71, slug: "feature-engineering-labeling", title: "Feature Engineering, Labeling and Leakage",
        summary: "The part of ML that decides everything - building point-in-time features, labeling with the triple barrier, and stamping out leakage.",
        learn: ["Point-in-time features", "Stationary feature transforms", "Fixed-horizon labels", "The triple-barrier method", "Meta-labeling", "Leakage audits"], tags: ["NSE"] },
      { n: 72, slug: "portfolio-construction-risk", title: "Portfolio Construction, Risk Models, VaR and Stress",
        summary: "From many signals to one book - mean-variance and its fixes, position sizing and Kelly, risk models, and VaR, CVaR and stress testing for the tail.",
        learn: ["Mean-variance and its limits", "Risk parity and vol targeting", "Kelly and fractional Kelly", "Factor risk models", "VaR and CVaR", "Stress testing the tail"], tags: ["NSE", "INDEX"] },
    ],
  },
  {
    id: "I",
    name: "Production, Compliance & Career",
    desc: "Taking research live - infrastructure, the production pipeline, monitoring, compliance, and the capstone project.",
    chapters: [
      { n: 73, slug: "data-infrastructure", title: "Data and Research Infrastructure",
        summary: "The unglamorous backbone - tick vs bar storage, point-in-time datasets, time-series databases and a reproducible research environment.",
        learn: ["Tick / L1 / L2 / L3 storage", "Point-in-time datasets", "Time-series databases", "Cleaning and corporate actions", "Reproducible pipelines", "Cost and scale"], tags: ["NSE"] },
      { n: 74, slug: "research-to-production", title: "The Research-to-Production Pipeline",
        summary: "Closing the gap between a notebook and a live bot - shared code paths, configuration, parity testing and a disciplined deployment process.",
        learn: ["The research-production gap", "Shared signal code", "Config and parameters", "Backtest-live parity", "Staging and deployment", "Versioning and rollback"], tags: ["NSE"] },
      { n: 75, slug: "live-trading-system-design", title: "Live Trading System Design",
        summary: "The architecture of a running trading system - the OMS and PMS, the order and position lifecycle, state management and resilience under failure.",
        learn: ["OMS and PMS roles", "Order and position state", "Event loops and queues", "Idempotency and recovery", "BCP and disaster recovery", "Designing for failure"], tags: ["NSE"] },
      { n: 76, slug: "monitoring-reconciliation", title: "Monitoring, Reconciliation and Incident Handling",
        summary: "Keeping a live book honest and alive - real-time monitoring, end-of-day reconciliation, logging, alerting and a calm incident response.",
        learn: ["Live monitoring and dashboards", "Risk-limit alerts", "Trade and position reconciliation", "Logging and audit trails", "Incident response", "Post-mortems"], tags: ["NSE"] },
      { n: 77, slug: "sebi-algo-compliance-ethics", title: "SEBI Algo Compliance and Ethics",
        summary: "Trading inside the rules - the SEBI algo framework, system audit and governance duties, market-conduct rules, and the ethics of automated trading.",
        learn: ["The SEBI algo framework", "System audit and governance", "Cyber resilience duties", "Market-conduct rules", "Manipulation red lines", "Ethics and responsibility"], tags: ["NSE"] },
      { n: 78, slug: "capstone", title: "Capstone: A Full Indian Quant Research Project",
        summary: "Everything together - a real edge taken from hypothesis through microstructure-aware data, model, portfolio, risk, an honest backtest and a path to production.",
        learn: ["Framing a hypothesis", "Microstructure-aware data", "Building the model", "Portfolio and sizing", "Honest backtest and costs", "Toward production"], tags: ["NSE", "INDEX", "NFO"] },
    ],
  },
];

export const CHAPTERS = PARTS.flatMap((p) =>
  p.chapters.map((c) => ({ ...c, part: p.id, partName: p.name })),
).sort((a, b) => a.n - b.n);

export function chapterBySlug(slug) {
  return CHAPTERS.find((c) => c.slug === slug) || null;
}

export const TAG_CLASS = { NSE: "nse", NFO: "nfo", MCX: "mcx", INDEX: "idx", BSE: "nse", CDS: "idx" };
