// Single source of truth for the "Quantitative Trading" learning portal:
// 36 chapters across 8 modules, focused on Indian market structure and the
// mathematics of trading - taught Zerodha-Varsity style, data from OpenAlgo.
// Slugs form the /quant/<slug> URLs - keep them stable.

export const SERIES_TITLE = "Quantitative Trading";
export const SERIES_SUB =
  "A hands-on path from trader to quant - market structure, the mathematics of markets, and how to find a real edge, all grounded in Indian markets and the OpenAlgo SDK.";

export const PARTS = [
  {
    id: "A",
    name: "The Quant & the Indian Market Map",
    desc: "Who quants are, how Indian markets are wired, and what a trade really costs.",
    chapters: [
      { n: 1, slug: "what-is-a-quant", title: "What a Quant Actually Does",
        summary: "The real job behind the word - the roles, the skill stack, and how a quant thinks differently from a discretionary trader.",
        learn: ["Quant vs discretionary thinking", "Researcher / trader / developer", "Sell-side vs buy-side vs prop vs HFT",
          "The quant skill stack", "Signal vs noise", "Myths vs reality"], tags: ["NSE", "INDEX"] },
      { n: 2, slug: "indian-market-map", title: "The Map of Indian Markets",
        summary: "NSE and BSE, cash and derivatives, the headline indices, and the cast of participants who move prices.",
        learn: ["NSE vs BSE", "Cash vs derivatives segments", "Nifty, Bank Nifty, FinNifty, Sensex",
          "Retail, HNI, FII/FPI, DII, prop", "Market-cap structure", "Reading who is trading"], tags: ["NSE", "INDEX"] },
      { n: 3, slug: "market-plumbing", title: "The Plumbing: SEBI, Clearing & Settlement",
        summary: "How a trade actually completes - the regulator, the exchanges, clearing corporations, depositories, and T+1/T+0.",
        learn: ["SEBI's role", "Exchanges vs clearing corps", "NSDL & CDSL depositories",
          "The life of a trade", "T+1 and the T+0 beta", "Why settlement matters to a quant"], tags: ["NSE"] },
      { n: 4, slug: "cost-of-trading", title: "The True Cost of a Trade",
        summary: "STT, stamp duty, exchange and SEBI charges, GST, brokerage - building the all-in cost model that quietly kills most edges.",
        learn: ["STT by segment", "Stamp duty & exchange charges", "SEBI fees & GST",
          "Brokerage & DP charges", "An all-in cost function", "Why costs make or break strategies"], tags: ["NSE", "NFO"] },
    ],
  },
  {
    id: "B",
    name: "Market Microstructure",
    desc: "How prices are really formed - the order book, liquidity, impact, and speed.",
    chapters: [
      { n: 5, slug: "limit-order-book", title: "The Limit Order Book",
        summary: "Bids, asks, depth and price-time priority - the live queue where every Indian trade is matched.",
        learn: ["Bids, asks & depth", "Market vs limit orders", "Price-time priority",
          "Indian order types (IOC, SL, GTT)", "Disclosed / iceberg quantity", "Reading depth() data"], tags: ["NSE"] },
      { n: 6, slug: "price-formation", title: "Price Formation & Auctions",
        summary: "The matching engine, the tick-size regime, and the pre-open and closing call auctions that bookend the day.",
        learn: ["How a trade matches", "Tick size & its effects", "The pre-open call auction",
          "The closing auction", "Equilibrium price discovery", "Auction vs continuous trading"], tags: ["NSE", "INDEX"] },
      { n: 7, slug: "liquidity-and-impact", title: "Liquidity, Spread & Market Impact",
        summary: "Why your own order moves the price - spread, depth, resilience, and measuring impact in real names.",
        learn: ["Bid-ask spread components", "Depth & resilience", "Kyle's lambda (intuition)",
          "Amihud illiquidity", "Measuring impact in NSE names", "Liquidity as a cost"], tags: ["NSE"] },
      { n: 8, slug: "circuit-breakers", title: "Circuit Breakers, Bands & Surveillance",
        summary: "Index halts, scrip price bands, ASM/GSM and the F&O ban - and how they distort the signals you compute.",
        learn: ["Index circuit breakers", "Scrip price bands", "ASM & GSM lists",
          "The F&O ban period", "Upper/lower circuits", "Surveillance and your signals"], tags: ["NSE"] },
      { n: 9, slug: "order-flow", title: "Order Flow & Participants",
        summary: "Informed vs uninformed flow, participant-wise open interest, and reading FII/DII activity.",
        learn: ["Informed vs uninformed flow", "Participant-wise OI", "FII/DII flow data",
          "Toxicity & adverse selection", "Retail's growing footprint", "Flow as a signal"], tags: ["NSE", "NFO"] },
      { n: 10, slug: "hft-and-latency", title: "HFT, Colocation & Latency",
        summary: "The microstructure of speed - colocation at NSE, tick-by-tick data, latency arbitrage, and what's feasible for whom.",
        learn: ["What HFT actually does", "Colocation at NSE/BSE", "Tick-by-tick data",
          "Latency arbitrage", "The speed arms race", "Where retail quants can and can't play"], tags: ["NSE"] },
    ],
  },
  {
    id: "C",
    name: "The Mathematics of Markets",
    desc: "Probability and statistics for trading - explained in plain words, with charts.",
    chapters: [
      { n: 11, slug: "returns-and-distributions", title: "Returns & the Stylized Facts",
        summary: "Simple vs log returns and the empirical truths of markets - fat tails, volatility clustering, and the leverage effect.",
        learn: ["Simple vs log returns", "Fat tails vs the bell curve", "Volatility clustering",
          "The leverage effect", "Autocorrelation of returns", "Stylized facts on Nifty"], tags: ["NSE", "INDEX"] },
      { n: 12, slug: "probability-and-monte-carlo", title: "Probability & Monte Carlo",
        summary: "Random variables, expectation and variance, and using simulation to price what you can't solve by hand.",
        learn: ["Random variables & expectation", "Variance & standard deviation", "The normal and its failures",
          "Law of large numbers", "Monte Carlo simulation", "Simulating a strategy's outcomes"], tags: ["INDEX"] },
      { n: 13, slug: "inference-and-overfitting", title: "Inference & the Multiple-Testing Trap",
        summary: "Hypothesis tests, p-values, and why testing 500 ideas almost guarantees a fake winner.",
        learn: ["Sampling & estimates", "Hypothesis testing", "p-values, honestly",
          "The multiple-testing problem", "False discovery", "Why most backtests lie"], tags: ["NSE"] },
      { n: 14, slug: "stationarity-random-walk", title: "Stationarity & the Random Walk",
        summary: "Why prices wander unpredictably, how to test for it, and what the efficient-market idea gets right and wrong.",
        learn: ["The random walk", "Stationary vs non-stationary", "ADF & KPSS tests",
          "Why prices resist prediction", "The efficient market hypothesis", "Where the EMH cracks"], tags: ["NSE", "INDEX"] },
    ],
  },
  {
    id: "D",
    name: "Time Series & Econometrics",
    desc: "Modelling how today's market depends on yesterday's - mean reversion, volatility, regimes.",
    chapters: [
      { n: 15, slug: "time-series-models", title: "Time-Series Models (AR, MA, ARIMA)",
        summary: "The classic models for series that remember their past - and an honest look at what is and isn't forecastable.",
        learn: ["Autoregression (AR)", "Moving average (MA)", "ARIMA",
          "Fitting with statsmodels", "Forecasting returns vs vol", "What is truly predictable"], tags: ["NSE", "INDEX"] },
      { n: 16, slug: "volatility-modeling", title: "Volatility Modeling (GARCH)",
        summary: "Volatility has a memory - calm follows calm, storms cluster. ARCH, GARCH and EWMA make that precise.",
        learn: ["Why vol clusters", "EWMA volatility", "ARCH & GARCH (intuition)",
          "Fitting GARCH with arch", "Realized volatility", "Forecasting Nifty volatility"], tags: ["INDEX"] },
      { n: 17, slug: "mean-reversion-cointegration", title: "Mean Reversion & Cointegration",
        summary: "The man-and-his-dog idea behind pairs trading - two wandering prices on a leash that always snaps back.",
        learn: ["Mean reversion intuition", "Ornstein-Uhlenbeck", "Cointegration vs correlation",
          "Engle-Granger test", "The spread & z-score", "Half-life of reversion"], tags: ["NSE"] },
      { n: 18, slug: "regimes-and-breaks", title: "Regimes & Structural Breaks",
        summary: "Markets switch between calm bulls, grinding bears and violent shocks - detecting the regime you're in.",
        learn: ["Bull / bear / sideways regimes", "Volatility regimes", "Markov switching (intuition)",
          "Change-point detection", "Structural breaks", "Why a strategy stops working"], tags: ["INDEX"] },
    ],
  },
  {
    id: "E",
    name: "Derivatives, Volatility & Options",
    desc: "The options machine - pricing, the Greeks, the volatility surface, and trading vol itself.",
    chapters: [
      { n: 19, slug: "no-arbitrage", title: "No-Arbitrage & the Synthetic Future",
        summary: "The most powerful idea in pricing - free money can't exist - and how put-call parity builds a synthetic future you can price options against.",
        learn: ["The no-arbitrage principle", "Forwards & futures", "Cost of carry & basis",
          "Put-call parity", "The synthetic future", "Cash-futures basis in India"], tags: ["NFO", "INDEX"] },
      { n: 20, slug: "black76-greeks", title: "Black-76 & the Greeks",
        summary: "Why Indian F&O is priced with Black-76, not Black-Scholes - off the forward (the synthetic future) - and the Greeks that show how an option breathes: delta, gamma, vega, theta.",
        learn: ["Black-76 vs Black-Scholes", "Pricing off the forward", "Delta & gamma",
          "Vega & theta", "Implied volatility", "OpenAlgo Greeks on a Nifty option"], tags: ["NFO", "INDEX"] },
      { n: 21, slug: "volatility-surface", title: "The Volatility Surface & India VIX",
        summary: "Implied volatility, the skew and smile, the term structure, and reading India VIX as the market's fear gauge.",
        learn: ["Implied volatility", "The volatility smile & skew", "Term structure",
          "India VIX explained", "Weekly-expiry dynamics", "Reading the surface"], tags: ["NFO", "INDEX"] },
      { n: 22, slug: "trading-volatility", title: "Trading Volatility",
        summary: "Volatility as an asset - variance trades, gamma scalping, the vol risk premium, and Indian expiry-day effects.",
        learn: ["Volatility as an asset", "The volatility risk premium", "Gamma scalping",
          "Variance & straddle P&L", "Expiry-day effects", "Selling vs buying vol"], tags: ["NFO", "INDEX"] },
    ],
  },
  {
    id: "F",
    name: "Portfolio Construction & Risk",
    desc: "From one trade to a book - diversification, factors, sizing, and surviving the tail.",
    chapters: [
      { n: 23, slug: "portfolio-theory", title: "Portfolio Theory & Its Limits",
        summary: "Diversification as the only free lunch - mean-variance, the efficient frontier, and why it breaks in practice.",
        learn: ["Risk, return & covariance", "Diversification", "The efficient frontier",
          "Mean-variance optimisation", "Why it fails live", "Practical fixes"], tags: ["NSE", "INDEX"] },
      { n: 24, slug: "factor-models", title: "Factor Models & Equity Risk",
        summary: "The handful of forces - value, momentum, quality, size, low-vol - that drive most returns, built for India.",
        learn: ["CAPM & beta", "Fama-French factors", "Building India factors",
          "Momentum & value", "Quality & low-vol", "The factor zoo & caution"], tags: ["NSE"] },
      { n: 25, slug: "capital-allocation", title: "Capital Allocation & Sizing",
        summary: "How much to bet - Kelly, risk parity, volatility targeting and Black-Litterman, at the portfolio level.",
        learn: ["The Kelly criterion", "Fractional Kelly", "Risk parity",
          "Volatility targeting", "Black-Litterman (intuition)", "Allocating across strategies"], tags: ["NSE", "INDEX"] },
      { n: 26, slug: "tail-risk", title: "Tail Risk: VaR, CVaR & Stress",
        summary: "Your worst normal day, and the days that break the model - VaR, expected shortfall and stress testing.",
        learn: ["Value at Risk (VaR)", "Historical vs parametric VaR", "Expected shortfall (CVaR)",
          "Stress testing", "Drawdown control", "Indian shock case studies"], tags: ["NSE", "INDEX"] },
    ],
  },
  {
    id: "G",
    name: "Alpha: Finding & Validating an Edge",
    desc: "The research process, the strategy families, and how to know an edge is real.",
    chapters: [
      { n: 27, slug: "alpha-research-process", title: "The Alpha Research Process",
        summary: "Turning a hunch into a tested edge - hypothesis, data, test, validation: the scientific method for trading.",
        learn: ["Idea to hypothesis", "Designing a fair test", "Signal vs noise",
          "In-sample vs out-of-sample", "Decay & capacity", "A research checklist"], tags: ["NSE"] },
      { n: 28, slug: "statistical-arbitrage", title: "Statistical Arbitrage",
        summary: "Market-neutral trading of relationships - pairs, baskets, and the cash-futures arb that runs on every Indian desk.",
        learn: ["Pairs from cointegration", "Building the spread", "Z-score entries & exits",
          "Index arbitrage", "Cash-futures arb in India", "Market-neutral risk"], tags: ["NSE", "NFO"] },
      { n: 29, slug: "momentum-and-value", title: "Cross-Sectional Momentum & Value",
        summary: "The two workhorses of systematic equity - rank the universe, go long the best, short the worst.",
        learn: ["Cross-sectional vs time-series", "Momentum factor", "Value factor",
          "Ranking the NSE universe", "Building long-short books", "Combining factors"], tags: ["NSE"] },
      { n: 30, slug: "event-driven", title: "Event-Driven & Flow Strategies",
        summary: "Trading the calendar and the flows - earnings, index rebalancing, corporate actions and FII activity.",
        learn: ["Earnings drift", "Nifty index reconstitution", "Corporate actions",
          "F&O ban & expiry effects", "FII/DII flow signals", "Designing event trades"], tags: ["NSE", "NFO"] },
      { n: 31, slug: "market-making-execution", title: "Market Making & Optimal Execution",
        summary: "The other side of the trade - quoting both sides, managing inventory, and slicing big orders to hide impact.",
        learn: ["Providing liquidity", "Inventory management", "Adverse selection",
          "VWAP & TWAP", "Implementation shortfall", "Transaction cost analysis"], tags: ["NSE"] },
    ],
  },
  {
    id: "H",
    name: "Rigor, Infrastructure & the Profession",
    desc: "Backtesting honestly, the tooling that supports research, and the path to a quant career.",
    chapters: [
      { n: 32, slug: "backtesting-rigor", title: "Backtesting Without Fooling Yourself",
        summary: "The traps that turn a losing system into a beautiful backtest - look-ahead, survivorship, data snooping - and how to avoid them.",
        learn: ["Look-ahead bias", "Survivorship bias", "Data snooping & overfitting",
          "Walk-forward & CV", "Deflated Sharpe", "Realistic costs in tests"], tags: ["NSE"] },
      { n: 33, slug: "ml-in-quant", title: "Machine Learning in Quant: Promise & Peril",
        summary: "Where machine learning genuinely helps a quant, where it quietly leaks the future, and how to use it safely.",
        learn: ["Where ML helps vs hurts", "Feature & label leakage", "Train/test on time series",
          "Meta-labeling", "Feature importance", "Avoiding overfit ML"], tags: ["NSE"] },
      { n: 34, slug: "data-infrastructure", title: "Data & Research Infrastructure",
        summary: "The unglamorous backbone - tick vs bar data, point-in-time datasets, and the research-to-production pipeline.",
        learn: ["Tick / L1 / L2 / L3 data", "Point-in-time data", "Time-series databases",
          "Cleaning & corporate actions", "Research to production", "Reproducible pipelines"], tags: ["NSE"] },
      { n: 35, slug: "quant-career", title: "Building a Quant Career in India",
        summary: "The firms, the desks, the interviews and the ethics - a practical map to actually becoming a working quant.",
        learn: ["Firms & desks in India", "Buy-side vs sell-side roles", "The quant interview",
          "Probability & brainteasers", "SEBI algo compliance", "Ethics & responsibility"], tags: ["NSE"] },
      { n: 36, slug: "capstone", title: "Capstone: A Full Quant Research Project",
        summary: "Everything together - a real edge taken from hypothesis to microstructure-aware data, model, portfolio, risk and an honest backtest.",
        learn: ["Framing a hypothesis", "Microstructure-aware data", "Building the model",
          "Portfolio & sizing", "Honest backtest & costs", "Writing it up"], tags: ["NSE", "INDEX", "NFO"] },
    ],
  },
];

export const CHAPTERS = PARTS.flatMap((p) =>
  p.chapters.map((c) => ({ ...c, part: p.id, partName: p.name })),
).sort((a, b) => a.n - b.n);

export function chapterBySlug(slug) {
  return CHAPTERS.find((c) => c.slug === slug) || null;
}

export const TAG_CLASS = { NSE: "nse", NFO: "nfo", MCX: "mcx", INDEX: "idx", BSE: "nse", CDS: "idx" };
