// Runtime loader for the "Statistical Arbitrage" course. Reads pre-rendered chapter
// HTML from a bundled JSON module (generated by scripts/gen-stats-arb-content.mjs at
// build time). No filesystem access here, so it works on Cloudflare Workers.
import data from "./statsArbContentData.json";

const EMPTY = { html: "", toc: [], exCount: 0, hasContent: false };

export function loadChapter(n) {
  return data[String(n)] || data[n] || EMPTY;
}

export function chapterHasContent(n) {
  return loadChapter(n).hasContent;
}
