fig, ax = plt.subplots(1, 2, figsize=(13, 4.4))
sns.histplot(trades.trade_ret*100, bins=18, kde=True, color=C['blue'], ax=ax[0])
ax[0].axvline(0, color=C['red'], ls='--', lw=1.2)
ax[0].axvline(avg*100, color=C['green'], ls='-', lw=1.6, label=f'mean {avg*100:+.2f}%')
ax[0].set_title('Per-trade return (in-sample, gross)'); ax[0].set_xlabel('trade return (%)'); ax[0].legend(fontsize=9)
sns.histplot(trades.days, bins=15, color=C['amber'], ax=ax[1])
ax[1].axvline(HL, color=C['purple'], ls='--', lw=1.6, label=f'half-life {HL:.0f}d')
ax[1].set_title('Holding period'); ax[1].set_xlabel('days held'); ax[1].legend(fontsize=9)
plt.tight_layout(); plt.show()
