// Generated by scripts/gen-script-docs.mjs from content/script/nav.json. Do not edit.
import ScriptDocView, { scriptDocMetadata } from "@/components/script/ScriptDocView"

export const metadata = scriptDocMetadata("getting-started", "introduction")

export default function Page() {
  return <ScriptDocView section={"getting-started"} page={"introduction"} />
}
