// Generated by scripts/gen-script-docs.mjs from content/script/nav.json. Do not edit.
import ScriptDocView, { scriptDocMetadata } from "@/components/script/ScriptDocView"

export const metadata = scriptDocMetadata("language", "bars-and-history")

export default function Page() {
  return <ScriptDocView section={"language"} page={"bars-and-history"} />
}
